---
title: "Standard 8: Instructional Strategies"
output: 
  html_document: 
    theme: cerulean
    css: styles.css
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

----

The teacher understands and uses a variety of instructional strategies to encourage learners to develop deep understanding of content areas and their connections, and to build skills to apply knowledge in meaningful ways. 
 
----

### {.tabset .tabset-pills .tabset-fade}


#### Performance 8.1

<div style="padding-left:1px;">

Candidates plan instruction based on ELA curricular requirements and standards.

##### Evidence 1: Writing Sequences (329)

<div style="padding-left:40px;">

**Prompt**

This assignment is lesson planning to teach four genres of writing: fiction, personal narrative, argumentation, and research.  You will plan through five stages, which roughly correspond to pre-writing, writing, editing/evaluation. This will happen in five stages. A sample of this assignment will be provided.


**Samples**: 

1. Excellent performance:  [Fall '19](https://drive.google.com/file/d/14c-s3xbLpPA5GmTEN6by0G7BSe18HE3P/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1ZkdTqUm_k6N3Uq2QtqWo3mNrhPdECVP1/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/17pDWqY7JhXYMGLn_3AsjOaAbq3gZvLbv/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/13kLVUok2JNPxOQon43RJN_5W9mYZGq5b/view?usp=sharing)

3.  Poor performance: [Fall '19](https://drive.google.com/file/d/1dqjt2gg9v0hybme0MM1qyEYnPlZZ-8_T/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/14Xf-T9mwMUYTRy00l-hR_wAE-KqGKMqo/view?usp=sharing)
</div>

##### Evidence 2: Syllabus (329)
<div style="padding-left:40px;">

The syllabus for Teaching Writing in Secondary Schools (ENG 329) can be found here:  [Fall '19](https://drive.google.com/file/d/1e-1qbdwGxYMCaRPbk6JVTofBFhxvJKU1/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1mJ1igwM1BG8_lIGCEiOCDRZ7zzUA8Vk2/view?usp=sharing)

</div>


##### Evidence 3: Powerpoint on any topic addressed in the standards (329)
<div style="padding-left:40px;">

You can found powerpoints showing how students learn and prepare to teach writing in secondary schools based on ELA standards here: [Fall '19a](https://drive.google.com/file/d/1hAkg5fs7Q-kl1OkiBXN3sF8wSlKgG4Xt/view?usp=sharing), [Fall '19b](https://drive.google.com/file/d/1bBMzH2r04064kMu0Zb9OpQDrtjRyEPnB/view?usp=sharing), and [Winter '20](https://drive.google.com/file/d/1hHGg6N6ABgmn3y0sfsipchvE3vDspR0t/view?usp=sharing).

</div>


</div>

----

<footer></footer>