---
title: "Standard 5: Application of Content"
output: 
  html_document: 
    theme: cerulean
    css: styles.css
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

----

The teacher understands how to connect concepts and use differing perspectives to engage learners in critical thinking, creativity, and collaborative problem solving related to authentic local and global issues. 

----

### {.tabset .tabset-pills .tabset-fade}


#### Performance 5.1

<div style="padding-left:1px;">

Candidates design instruction related to language conventions. 


##### Evidence 1: Mini-lesson (ENG 329)

<div style="padding-left:40px;">

**Prompt**

Each of you will teach a 15-minute mini-lesson in our English 329 class. You will sign up for a Common Core Standard and then design a lesson that teaches some aspect of that standard. See the attached documents for guidance. The guidelines for the mini-lesson can be found [here](https://drive.google.com/file/d/1oq0f4gaOmDNQwarbh4AXD3NKmx4WzJby/view?usp=sharing).

**Samples**: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1nrSgFtXCjVs7haUtYb_DXttPjFqqO0BU/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1cLQaxNW1zg3W_Ot-8YF8TolAbDtNjrUL/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1TK1JtouF2VCSYh-ftUog1EYrEvDMOUvm/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1VzB-jgbyeiJr-O4G3KV18NtSBtD9iCTD/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1vDDKlePe9gzPC9sInDYpFvjvatXGcOX9/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1-5CWLSg5Gd_7SAo3WiSwTbG6TT0icDMq/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1qP7hfTCwKueAgB4hJPMVQHjLI7dY_1Ko/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1Jrh76s7sfKjLJTicaXCzyO98rLtPP2vz/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1PefFVCt_bJeavAFLrry5zDwvOlUtxV38/view?usp=sharing)

</div>

##### Evidence 2: Writing Sequences (ENG 329)
<div style="padding-left:40px;">
**Prompt**

This assignment is lesson planning to teach four genres of writing: fiction, personal narrative, argumentation, and research.  You will plan through five stages, which roughly correspond to pre-writing, writing, editing/evaluation. This will happen in five stages. A sample of this assignment will be provided.

**Samples**: 

1. Excellent performance:  [Fall '19](https://drive.google.com/file/d/14c-s3xbLpPA5GmTEN6by0G7BSe18HE3P/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1ZkdTqUm_k6N3Uq2QtqWo3mNrhPdECVP1/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/164snfLPRmVCQMbRLCWlF2xPX9ahTLw3f/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/17pDWqY7JhXYMGLn_3AsjOaAbq3gZvLbv/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/13kLVUok2JNPxOQon43RJN_5W9mYZGq5b/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1U-7cM_ocCY7GdObsWSbIGkppsgxeb0Z4/view?usp=sharing)

3.  Poor performance: [Fall '19](https://drive.google.com/file/d/1dqjt2gg9v0hybme0MM1qyEYnPlZZ-8_T/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/14Xf-T9mwMUYTRy00l-hR_wAE-KqGKMqo/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1ajT_V8JR9kezP14VQHvnOy9uw4zOAc7w/view?usp=sharing)
</div>


##### Evidence 3: Modeling from PowerPoint (ENG 329)
<div style="padding-left:40px;">
**Summary**

Students, together with the professor, do some in class work with the grammar points that are included in the following PowerPoints. We can see slides 4,5, and 6 of the first PowerPoint are ways for students to start thinking how to use conventions when teaching English. 

**PowerPoint I (Fall '19)**: you can find it [here](https://drive.google.com/file/d/1_CLzhjnk7YEYKtbIe-Kqv5U3TqdFzaUv/view?usp=sharing).

**PowerPoint II (Fall '19)**: you can find it [here](https://drive.google.com/file/d/1fgdUlMJvWj4lBoZYyj4u9dLg1XUycHXX/view?usp=sharing).

**PowerPoint III (Winter '20)**: you can find it [here](https://drive.google.com/file/d/1puVQJ__fQogdVO-UnPlnT7MkdBijg156/view?usp=sharing).

</div>


</div>

----


#### Performance 5.2

<div style="padding-left:1px;">

Candidates design instruction that promotes social justice and critical engagement.
 
 

##### Evidence 1: Literature Circles ~ Sociological role (ENG 356)

<div style="padding-left:40px;">

Actively participate in novel discussions by completing your assigned group role and speaking in your group discussions. Discussion will take place in class.

1. *Role: Sociological Lens*: The point of this role is to explore the role of power in a society. Many today are discussing social justice themes—this is an opportunity for you to be aware and join the conversation on this topic by exploring power within the context of literature. 
 

**Samples**: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1Cg2qMwNqeTX13pNrPieiJXIkdCOQOIb0/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1bzUwURqZ9euRKrbW524jtJbsi_5MZsow/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1vJ_KmIGflC8G_f7upFbeIUVveQqQjutK/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1-tAnXAd4FvG_2aPo4j7Px8br-6-9fmY4/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1LG19u0k_wygKTbc6Uxn60Uumb50pjQ_Q/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1yspuylfT4kShdCiZ6qotBR3c-iSO51tc/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1Hh9M080qEOybnahkxI2JLnwJ1ftA1jxO/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1s94HVIzWj_Cksxz-Pj9hHXXZgrPsaLd8/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1YzSc5KO0yHgE7sGzhk_4TVR7tByl1Htd/view?usp=sharing)

</div>

##### Evidence 2: Annotated Bibliography (ENG 329)
<div style="padding-left:40px;">

**Prompt**

You will sign up for one of the following topics:

1.	Social justice—what is it? How does it connect to the ELA classroom?—Standard 5B
2.	How do language and dialect affect literacy?—Standards 2A and 3A


Find at least three scholarly journal articles on that topic and compile the information into an annotated bibliography. Use MLA formatting for citation purposes. OWL@Purdue.edu will help you organize your annotated bibliography. (45 points for bibliography, 15 points for discussion, 60 total)

**Samples**:

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1C20BFY97qLt1DwKCUjc4xhvFHdzXZ-vO/view?usp=sharing)  / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/13VZLyMig1PvFeVyamKfc7gy3mi9o3Qn-/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1rn_oVabh1bfjd13hxtyynLY0RaNzKeO4/view?usp=sharing) / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/13VZLyMig1PvFeVyamKfc7gy3mi9o3Qn-/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1G84mOFKFVuzOW7pgDjmMW_bv8RtDpoEq/view?usp=sharing) / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/1zbvvvr4qqfY0BDEdt9e-KLRZLHJuXb58/view?usp=sharing)

</div>


##### Evidence 3: Literature Circles ~ Social Justice role (ENG 356)
<div style="padding-left:40px;">
**Prompt**

Actively participate in novel discussions by completing your assigned group role and speaking in your group discussions. Discussion will take place in class.

1. *Role: Social Justice Lens*: Publishers, editors, writers, and teachers work together when it comes to using Young Adult Literature in a classroom. Any of these groups of people post teaching ideas online.  For this literature circle role, you will create a lesson plan that focuses on a social justice theme. 

**Samples**: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1xMuEPoYG-p6qC-eG9sNiC27bcbjiafgj/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1qTrhz9N5K9Rp0RPmZM5sk_Y8XLWUDcjp/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1lQuOdFrDaUgJbu_sKCHrjaXMYYajNzKb/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1z2X88cvn1eFt0c8R820KJJAxGi8RoPGY/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1xiLp2EKBB4DLsPb_MpMmbSPLaQ9APm7N/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1Ap0bfbXZo4WAErsa-wOqNjnqKS5h5LkS/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1Hh9M080qEOybnahkxI2JLnwJ1ftA1jxO/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1VTQQoCv0K3lr5ie6JGJb_XCPphdNwi1C/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/10-ea85X523QAPwbB1Voo-Y6COnCWOv02/view?usp=sharing)
</div>


</div>


----



#### Performance 5.3

<div style="padding-left:1px;">
Candidates design instruction related to different texts, purposes, and complexities. 
 
 
##### Evidence 1: Unit Lesson Plan (ENG 430)

<div style="padding-left:40px;">

**Prompt**

Prepare a three-week calendar, and detailed lesson plans for two of those weeks on the novel House on Mango Street. Each daily lesson will be connected to Common State Standards for Language Arts. It should also reflect the guidelines and suggestions discussed in class.


**Samples**: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1-KLwD0MyRDtUvvsE6B84EMMlmy64i199/view?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / [Fall '20](https://drive.google.com/file/d/1HyARrSMpFw2-fz-PSFyq8WFgY8P3nJMI/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1pUg4Inq9-D8XUrAqLdAK3DyKffv9348f/view?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / Fall '20 (missing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1zsj6lZJePoO8659M-wzQoVPl0_yzeccX/view?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / [Fall '20](https://drive.google.com/file/d/1_p9myCuiVKq_hUvz4DTW9ctCThuJgopo/view?usp=sharing)


</div>

##### Evidence 2: Education 461 Syllabus (ED 461)
<div style="padding-left:40px;">

The Syllabus for Reading in the Content Area (ED 461) can be found here [Fall '19/ Winter '20](https://drive.google.com/file/d/1-5Qafm2F34VBLWAcDB37yYS_FKbYpgvD/view?usp=sharing)

</div>


##### Evidence 3: Literacy I/II Syllabus (ED 344-345)
<div style="padding-left:40px;">

The syllabus for Literacy I (ED 344) can be found here [Fall '19/ Winter '20](https://drive.google.com/file/d/1ts8ctKOL7kQsUK88bZbyESgeOhwAZaEl/view?usp=sharing) and the one for Literacy II (ED 345) can be found here [Fall '19/ Winter '20](https://drive.google.com/file/d/1GmYkKdMwOHFXy2FjLLmlLi7aNgOlN5mY/view?usp=sharing).



</div>


</div>

----

#### Performance 5.4
<div style="padding-left:1px;">

Candidates design instruction related to speaking and listening. 
 
##### Evidence 1: Literature Circles ~ LitLinks role (ENG 356)

<div style="padding-left:40px;">

**Prompt**

Publishers, editors, writers, and teachers work together when it comes to using Young Adult Literature in a classroom. Any of these groups of  people post teaching ideas online.  For this literature circle role, you will create a document that gives links and advice on teaching a Young Adult novel. 

Parts of the LitLinks:

1.	Title and Summary. Please provide a brief summary of the text. -3 points
2.	Links to sites about two different themes in the book. Please provide a description of the links. If possible, provide modern day connections. –10 points
3.	Links to at least two teaching ideas. Please provide a description of the links. Choose activities that would serve a diverse group. –12 points

**Samples**:

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1vsU6LV1xoRqCD-rE-eS0lQIT02w67gX6/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1Yawq5PqjscSCQaU16jXqCLvYZaohNzcK/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/12fYlLrJ4-2FTNh1MMXDIz4CR6-THwirn/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1pZbtcAj85PTEt-XA4InYzVupzMEQDItn/view?usp=sharing)  / [Winter '20](https://drive.google.com/file/d/1FMncORFpmEH6pDzxbUMxcxCjI3uZkyUJ/view?usp=sharing)/ [Fall '20](https://drive.google.com/file/d/18reC5uGSOExvvIBoUpcebajIN1LQo5nr/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1eYqYIrtLYLpfxvu_qJcchiRELGZvIdY3/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1SCmqaSPVEvI8dUBSa0KIJMYgYRglssKV/view?usp=sharing)/ [Fall '20](https://drive.google.com/file/d/1iBiv6rywfTjnGF6n6bahqSxtUUH-BUK4/view?usp=sharing)

</div>

##### Evidence 2: Literature Circles - Passage Finder role (ENG 356)
<div style="padding-left:40px;">
**Prompt**

Actively participate in novel discussions by completing your assigned group role and speaking in your group discussions. Discussion will take place in class.

1. *Role: Passage Finder and Questioner Lens*: For this role, find 5-8 memorable quotes. Write them in the spaces below. Beside each quote, write a sentence or two discussing its significance. (You may make connections to your personal context.) Additionally, you must come up with 6 questions about the book that could be discussed. Record the questions below. Write in responses that the group gives you to at least three of the questions. 

**Sample**: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1Iz2o2OZdEa7OyIWcgr7ezt-E3qJ89Pji/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1kX4aVm7H33NIBLDQypPXUHNMV4pr75AN/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1Y0y-SXFrl2oDbyimIKdP3tqPk56wO-Gp/view?usp=sharing)

2. Average Performance: [Fall '19](https://drive.google.com/file/d/11pxDiCQwn_otvdtsep1952SJcDaYDdqW/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1bDxAxBNL0f31JLZo1wlU0LEmOKdoranm/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1jFVn-qsLc7QqEqGOK7zbK6LuCGq_mOuY/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1X5-P1EJU1YYO4yxoVHzk4Ft3lW7k-ME6/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/12r1Yq4Waa9u2cT6gsxarZlG8KAkL0EdN/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1Z4CqIX8vLIYUGDwvmBbdVdM9QDFkcR_B/view?usp=sharing)
</div>


##### Evidence 3: Writing Sequences (329)
<div style="padding-left:40px;">


**Prompt**

This assignment is lesson planning to teach four genres of writing: fiction, personal narrative, argumentation, and research.  You will plan through five stages, which roughly correspond to pre-writing, writing, editing/evaluation. This will happen in five stages. A sample of this assignment will be provided.

**Samples**: 

1. Excellent performance:  [Fall '19](https://drive.google.com/file/d/14c-s3xbLpPA5GmTEN6by0G7BSe18HE3P/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1ZkdTqUm_k6N3Uq2QtqWo3mNrhPdECVP1/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/164snfLPRmVCQMbRLCWlF2xPX9ahTLw3f/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/17pDWqY7JhXYMGLn_3AsjOaAbq3gZvLbv/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/13kLVUok2JNPxOQon43RJN_5W9mYZGq5b/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1U-7cM_ocCY7GdObsWSbIGkppsgxeb0Z4/view?usp=sharing)

3.  Poor performance: [Fall '19](https://drive.google.com/file/d/1dqjt2gg9v0hybme0MM1qyEYnPlZZ-8_T/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/14Xf-T9mwMUYTRy00l-hR_wAE-KqGKMqo/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1ajT_V8JR9kezP14VQHvnOy9uw4zOAc7w/view?usp=sharing)

</div>


</div>

----

<footer></footer>