---
title: "Standard 3: Learning Environments"
output: 
  html_document: 
    theme: cerulean
    css: styles.css
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

----

The teacher works with others to create environments that support individual and collaborative learning, and that encourage positive social interaction, active engagement in learning, and self-motivation. 

----


### {.tabset .tabset-pills .tabset-fade}


#### Performance 3.1

<div style="padding-left:1px;">

Candidates create inclusive learning environments. **Rationale can be found** [**here**](https://drive.google.com/file/d/1c1ryqMtMn_MQESkMgCU3hkDqJPk_J4vs/view?usp=sharing)

##### Evidence 1: Observations 1-5 (ENG 329)

<div style="padding-left:40px;">

*Prompt*

Fifteen observations in an ELA classroom setting with a mentor teacher. You will choose one topic to observe at each of your first five observations; you will choose a different topic at each new observation. As you type each observation, you will need to do the following: write ½ a page on what you learned in your Lab PLC group concerning the topic, then write the rest of your paper on your observations in connection to that topic. 

Topics:

1.	Social justice—what is it? How does it connect to the ELA classroom? (**What is the teacher doing to promote social justice**? What is effective? Why?)—Standard 5B
2.	How do **language and dialect affect literacy**? (What are teachers doing to address this in the classroom?)—Standards 2A and 3A

After completing the observation, look at your data. Now type, at the bottom of your observation (chart), your response to the following:

1.	What is the data telling you? Are there any patterns you notice? (two paragraphs)
2.	What have you learned from your observation and analysis? (two paragraphs)

*Samples*: 

1. Excellent performance: [Fall '19](https://docs.google.com/document/d/1vEfiTp1k0XhW4CRNuea64RAzKgY-BPKcrjsX2TjquVE/edit?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1rHhyFszJyjkiLKfMK8uAuEYgEF_0WyKy/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1U7avkpDmOcIrxoKXvhbgRQFz82mewPjG/view?usp=sharing)

2. Average performance: [Fall '19](https://docs.google.com/document/d/1KcOnW8LNr0eUb5iysLl7MoHl08udoGDz255Odja_ICI/edit?usp=sharing) / [Winter '20](https://drive.google.com/file/d/10Azd6sukwlDdSLWgZ3YVcDr0NCI1_uiy/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1DM5aQ1hPjnFyxFoJHWOMioYBZcIpResj/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1_NG4IESOrYddT7vBttDoHddVHPzSwtPD/view?usp=sharing) / [Winter '20](https://docs.google.com/document/d/1YvrJMY98Y7NO5fNH_cVyIpS2iR7e4PKm3CRJ5ldm_DM/edit?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1zAofc0YquvNYktL7tCBgTv_mwnVYCi16/view?usp=sharing)

</div>

##### Evidence 2: Annotated Bibliography Lab (ENG 329)
<div style="padding-left:40px;">
*Prompt*

You will sign up for one of the following topics:

1.	Social justice—what is it? How does it connect to the ELA classroom?—Standard 5B
2.	**How do language and dialect affect literacy**?—Standards 2A and 3A


Find at least three scholarly journal articles on that topic and compile the information into an annotated bibliography. Use MLA formatting for citation purposes. OWL@Purdue.edu will help you organize your annotated bibliography. (45 points for bibliography, 15 points for discussion, 60 total)


*Samples*:

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1C20BFY97qLt1DwKCUjc4xhvFHdzXZ-vO/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1Fz0vJseigakEzuHv-qp7WiegFp6cbmZo/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/13VZLyMig1PvFeVyamKfc7gy3mi9o3Qn-/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/13I6TK57Qefvd-ok2F76hDai66Ke3augw/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1tkEsRhyizYBScIrMJPQc3kjotTL0x334/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/13VZLyMig1PvFeVyamKfc7gy3mi9o3Qn-/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1G84mOFKFVuzOW7pgDjmMW_bv8RtDpoEq/view?usp=sharing)/ [Winter '20](https://drive.google.com/file/d/1W9GplP3c70V4Kxms-qNIRBRuRV8_i35Q/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1zbvvvr4qqfY0BDEdt9e-KLRZLHJuXb58/view?usp=sharing)

</div>


##### Evidence 3: Writing Sequences (ENG 329)
<div style="padding-left:40px;">
*Prompt*

This assignment is lesson planning to teach four genres of writing: fiction, personal narrative, argumentation, and research.  You will plan through five stages, which roughly correspond to pre-writing, writing, editing/evaluation. This will happen in five stages. A sample of this assignment will be provided.

*Samples*: 

1. Excellent performance:  [Fall '19](https://drive.google.com/file/d/1_kWkMZvHoM_ESJuJoU9gzY6dKFa4yOS8/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1jrO1MC9bSf8wAh6QyHQQEgJxyvfkVSwA/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1IAyu53S4pijiYy4Jyhvv2quH7oRw0xgL/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/19k3GIgLH6YpRseAADKI8SffD2eza9V_V/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1yPqAetmbZKgaq9aHiccfGXiAyGdH4KH7/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1MXCZOinLPeyyM8SOjY58tVTGVCL34K6r/view?usp=sharing)

3.  Poor performance: [Fall '19](https://drive.google.com/file/d/1RRcmSvpQTLdJtpDpalrK5BSKT1mIBflH/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/122UGUOiGYSpNYzLMP03BwZz5Ejpfm9_C/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1FICaQuU2i7-KrQ2T4BdhoIZ7Mj2WgWLg/view?usp=sharing)

</div>

</div>

</div>


----

<footer></footer>