---
title: "Standard 7: Planning for Instruction"
output: 
  html_document: 
    theme: cerulean
    css: styles.css
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>---
title: "Standard 6: Assessment"
output: 
  html_document: 
    theme: cerulean
    css: styles.css
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

----

The teacher plans instruction that supports every student in meeting rigorous learning goals by drawing upon knowledge of content areas, curriculum, cross- disciplinary skills, and pedagogy, as well as knowledge of learners and the community context. 
 
----

### {.tabset .tabset-pills .tabset-fade}


#### Performance 7.1

<div style="padding-left:1px;">

Candidates plan instruction which reflects curriculum integration. **Rationale can be found** [**here**](https://drive.google.com/file/d/1vjTtDqg_dSO1O5VMk-kr8Cyj_xGZiNvp/view?usp=sharing)


##### Evidence 1: Writing Sequences (ENG 329)

<div style="padding-left:40px;">

*Prompt*

**This assignment is lesson planning** to teach four genres of writing: fiction, personal narrative, argumentation, and research. **You will plan through five stages**, which roughly correspond to pre-writing, writing, editing/evaluation. This will happen in five stages. A sample of this assignment will be provided.

*Samples*: 

1. Excellent performance:  [Fall '19](https://drive.google.com/file/d/1Yv8ya8w0mCdPv03ECYh4nqZrUM5Yj_01/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1IAPYiLOoohmYCGMEjp--RUtufI-RRhFu/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1G4KyuIUaZNI8FLSnh-IM9xzv0ZGiDM0O/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1I2-1t6OsXJI1AkHXrv9m9U5GNGJCaHiD/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1s-55vqxyZ32cDej-vlqsg-6H6NBlPq-C/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1fA8nAhY3yCShzz8xi59WNRHddOT0ljZO/view?usp=sharing)

3.  Poor performance: [Fall '19](https://drive.google.com/file/d/1Xbd9GBmCku6RYqq40UKpval8F1qYd-6p/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1SNGsey55DqKYmTXEKRMJ0hjAJkYVDUZb/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1dc3oqatx8RiE8ye2GSHNXVcbR-nZcAnv/view?usp=sharing)
</div>

##### Evidence 2: Unit Lesson Plan (ENG 430)
<div style="padding-left:40px;">

*Prompt*

Prepare a three-week calendar, and **detailed lesson plans** for two of those weeks on the novel House on Mango Street. Each daily **lesson will be connected to Common State Standards for Language Arts**. It should also reflect the guidelines and suggestions discussed in class.


*Samples*: 

1. Excellent performance: [Fall '19](https://docs.google.com/document/d/1lz2lLxMRwlq_Zim7IV24ZxZou6kHGI4DkIo3KnAA6yI/edit?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / [Fall '20](https://drive.google.com/file/d/1ZMm0WNaXMGq5bJrDzOzfBNHOCIoCl_xc/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1uGf1pmoXWI0rQoGUU1mUx-9_c4gbxlsu/view?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / Fall '20 (missing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/11jKLsc7CtHZ5hS5YsxCaNL7X-q2txzQ1/view?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / [Fall '20](https://docs.google.com/document/d/1ek8oTB2U03HrI9bDoNfLtBKeO9Hmpe5CtWFpOOWw1pg/edit?usp=sharing)
</div>


##### Evidence 3: Mini-Lesson (ENG 329)
<div style="padding-left:40px;">

*Prompt*

You will teach a minimum of three times. You can work this out with your mentor teacher. This may be for a full or partial class period. Please submit **your lesson plan** to me via email three days in advance of teaching. Then, I can give you some feedback and your mentor teacher can give you some feedback. Remember, your mentor teacher is still held responsible for what you teach—please make him or her a big part of your planning process. These elements need to be in your lesson plan to receive full credit: objective, standard, assessment, hook, I DO, WE DO, THEY DO, closure, and enough detail that a sub could teach your lesson. You may want to ask your mentor teacher for lesson plan templates that have been helpful to him or her. (Standard 8A (Parts of 4 and 5—depending on the lesson)).

*Samples*: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1Ss0FqKemPJu4RDw17N0LUjr5hIM18Wpt/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1Rsj2BIjNH9yTZV9WRCGePvsWroaREm_g/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1EAG6XerpoAVMsxwDQfhFG1AachXbhCev/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/11rMkVjkrHqIWmTFrTs91yF4Z4_dpLJmX/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1GYeaLQzlab4bbcKJaft_EHQibqRjikPs/view?usp=sharing)  / [Fall '20](https://drive.google.com/file/d/1qFVTyGARf4XOAlTKSDQITM0pG18kBs_N/view?usp=sharing)

3. Poor Performance: [Fall '19](https://docs.google.com/document/d/16Y0oXwukSb7Ts9zwmBLyr6odbNtbFF4YsobbL1JQxNY/edit?usp=sharing) / [Winter '20](https://drive.google.com/file/d/16UwgGst9hCP2G886535KVRsVtoB8Ooa_/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1zosMKvi764wYVIBp0E85_Q_u2NgnZz86/view?usp=sharing)

</div>


</div>

----


#### Performance 7.2

<div style="padding-left:1px;">

Candidates plan learning experiences in reading.**Rationale can be found** [**here**](https://drive.google.com/file/d/137gSVx3JSvwwk_Q7ljIqGaw6bNLCTVLK/view?usp=sharing)
 
##### Evidence 1: Unit Lesson Plan (ENG 430)

<div style="padding-left:40px;">

*Prompt*

Prepare a three-week calendar, and detailed lesson plans for two of those weeks on the novel House on Mango Street. Each daily lesson will be connected to Common State Standards for Language Arts. It should also reflect the guidelines and suggestions discussed in class.yFPmJgANX2M/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1MadXX0_yswOW1-XdRBDAxAA_oPpgLnxg/view?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / Fall '20 (missing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1V5drcKBj1n0narTEB8X-_iDxS1Tk3XCs/view?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / [Fall '20](https://docs.google.com/document/d/13y7c2AeHf4XBnokfDKJczsE2gAfflYPB_OtA522nmA0/edit?usp=sharing)

</div>

##### Evidence 2: Education 461 Syllabus (ED 461)
<div style="padding-left:40px;">

The Syllabus for Reading in the Content Area (ED 461) can be found here [Fall '19/ Winter '20](https://drive.google.com/file/d/1-5Qafm2F34VBLWAcDB37yYS_FKbYpgvD/view?usp=sharing) / [Fall '20](https://docs.google.com/document/d/1MZ1uFxWnv8VSDIXsGZimitpNilbxY8hvAMNZ8pFgnWE/edit?usp=sharing)

</div>



*Samples*: 

1. Excellent performance: [Fall '19](https://docs.google.com/document/d/10fdC2Dj6_-XcLYKEHxCRdaftRkN4JxEW2PVQTAOvF7g/edit?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / [Fall '20](https://drive.google.com/file/d/1tknlLdcyA72e8v4uVOUay

##### Evidence 3: Literacy I/II Syllabus (ED 344-345)
<div style="padding-left:40px;">

The syllabus for Literacy I (ED 344) can be found here [Fall '19/ Winter '20](https://drive.google.com/file/d/1ts8ctKOL7kQsUK88bZbyESgeOhwAZaEl/view?usp=sharing), [Fall'20/ Winter '21](https://drive.google.com/file/d/1eYCiEyRAvkkvOuChICUQahdocnpf5zAj/view?usp=sharing), and the one for Literacy II (ED 345) can be found here [Fall '19/ Winter '20](https://drive.google.com/file/d/1GmYkKdMwOHFXy2FjLLmlLi7aNgOlN5mY/view?usp=sharing).

</div>


</div>


----



#### Performance 7.3

<div style="padding-left:1px;">
Candidates plan experiences that utilize different approaches and technologies.**Rationale can be found** [**here**](https://drive.google.com/file/d/1D-JfNFTA3P5v9dFBVZ1I45gDCPEpd90h/view?usp=sharing)
 
##### Evidence 1: Writing Sequences (ENG 329)

<div style="padding-left:40px;">

*Prompt*

This assignment is lesson planning to **teach four genres of writing**: fiction, personal narrative, argumentation, and research.  You will plan through five stages, which roughly correspond to **pre-writing, writing, editing/evaluation**. This will happen in five stages. A sample of this assignment will be provided.

*Samples*: 

1. Excellent performance:  [Fall '19](https://drive.google.com/file/d/1aHoQd6vK3Heolen7KJsHHCkD6N9ls4Un/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/13bQmAc1e9pnmjxGE_oDUz4iSEYArjPFG/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1Iu7y6BmzkSRJ0Z4KrJkNNerHBOnBUizK/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1cA4BhLr0LMo3g5Hy-XfIw98KQm9TxDr4/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1MQlsoJBmqnBQ53Akr8BkFBquEvmcZ-3h/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1-EV9QTlAlelxdSf0e4XP-f_3SEcDpOW7/view?usp=sharing)

3.  Poor performance: [Fall '19](https://drive.google.com/file/d/1MY3KqhpOzwYMe6B59cPDwFzt8zafBoQx/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1gvXh3Cwtd-_Eg9cThnHDq3Tl3awxp1kq/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1zSOMHtEp6Mc5OwC7iikq-ZPrCuZXXFmE/view?usp=sharing)
</div>

</div>

##### Evidence 2: Lesson Unit Plan (ENG 430)
<div style="padding-left:40px;">


*Prompt*

Prepare a three-week calendar, and detailed lesson plans for two of those weeks on the novel House on Mango Street. Each daily lesson will be connected to Common State Standards for Language Arts. It should also reflect the guidelines and suggestions discussed in class.

*Samples*: 

1. Excellent performance: [Fall '19](https://docs.google.com/document/d/1zbyndHJFN0kfW5IWowImlJaDbDp7d2cH0MhXCcr7U6M/edit?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / [Fall '20](https://drive.google.com/file/d/1Iuu4vzicAm5k8rJ4Qz_Z4wtyxg0ASzwO/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1G5wdvBVAJUuJNYRGK6oXcZAp5qorQEyy/view?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / Fall '20 (missing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1OJuoj6jThcFxCYOQi4_E6CBA8v8r7fdS/view?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / [Fall '20](https://docs.google.com/document/d/1t_0h1EWYDgiVHT6JMqAm4_n-V64CBqFSDKbonE2OGZQ/edit?usp=sharing)
</div>


##### Evidence 3: Literature Circles - LitLinks Role (ENG 356)
<div style="padding-left:40px;">
*Prompt*

Publishers, editors, writers, and teachers work together when it comes to using Young Adult Literature in a classroom. Any of these groups of  people post teaching ideas online.  For this literature circle role, you will create a document that gives links and advice on teaching a Young Adult novel. 

Parts of the LitLinks:

1.	Title and Summary. Please provide a brief summary of the text. -3 points
2.	Links to sites about two different themes in the book. Please provide a description of the links. If possible, provide modern day connections. –10 points
3.	Links to at least two teaching ideas. Please provide a description of the links. Choose activities that would serve a diverse group. –12 points


*Samples*:

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1zqFGZABV5YGl9leVtjxzh2iH-6GqwpZF/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1G22C3vurC-a2Gedwg7ur-2oylFNhsTK-/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1HOk7A_63nC4PCXOOd6Jaf9MK7ExE4Ocj/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1zu11jH1GxcyxcvocqR2Du8SFVz2-gr5_/view?usp=sharing)  / [Winter '20](https://drive.google.com/file/d/1n-6E6eamhd8YH5ZRUBVnLtXmWEt-DIjv/view?usp=sharing)/ [Fall '20](https://drive.google.com/file/d/1BA1_ZfZ7D1WPi_rcIHohryyaWU5n95Lw/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1pM5mTA5W7ex2s4aZOZIDJz-B_5B1he0c/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1HVqKjNmNHi5XK3Sufwoya_CjCXlGxFIv/view?usp=sharing)/ [Fall '20](https://drive.google.com/file/d/1Deo2vbsVax9-a38Ed0z7MC3WcR4xuAcf/view?usp=sharing)


</div>

----

#### Performance 7.4
<div style="padding-left:1px;">

Candidates plan learning experiences utilizing a range of different texts. **Rationale can be found** [**here**](https://drive.google.com/file/d/1IHn-rnvdltbh-Z53saJTD_o_VPyccrmV/view?usp=sharing) 
 
##### Evidence 1: to be determined

<div style="padding-left:40px;">

*Prompt*

1. Excellent Performance (sample)

2. Average Performance (sample)

3. Poor Performance (sample)
</div>

##### Evidence 2: Lesson Unit Plan (ENG 430)
<div style="padding-left:40px;">


*Prompt*

Prepare a three-week calendar, and detailed lesson plans for two of those weeks on the novel House on Mango Street. Each daily lesson will be connected to Common State Standards for Language Arts. It should also reflect the guidelines and suggestions discussed in class.


*Samples*: 

1. Excellent performance: [Fall '19](https://docs.google.com/document/d/1vXrVyLB1LsUNhFyNbzZqoE6SPtXxUQvKFiXL2-CoiWg/edit?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / [Fall '20](https://drive.google.com/file/d/1KtiPh1OuYphCO8HwB79luOaBmRPw0lVB/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1sBeBn3t2ejPhWfWKFY9PO0DHHd_rWrai/view?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / Fall '20 (missing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1JNmrtFV8mErdEArtBccDxxkIUcz4L5qR/view?usp=sharing) / (Winter '20)(to be collected from Sister Soper's class) / [Fall '20](https://docs.google.com/document/d/1qsDrzioCWu-ba4HNIjpWv4wXdEiPRnkMOPOFsBw6HF0/edit?usp=sharing)

</div>


##### Evidence 3: Literature Circles - LitLinks Role (ENG 356)
<div style="padding-left:40px;">
*Prompt*

Publishers, editors, writers, and teachers work together when it comes to using Young Adult Literature in a classroom. Any of these groups of  people post teaching ideas online.  For this literature circle role, you will create a document that gives links and advice on teaching a Young Adult novel. 

Parts of the LitLinks:

1.	Title and Summary. Please provide a brief summary of the text. -3 points
2.	Links to sites about two different themes in the book. Please provide a description of the links. If possible, provide modern day connections. –10 points
3.	Links to at least two teaching ideas. Please provide a description of the links. Choose activities that would serve a diverse group. –12 points


*Samples*:

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1Jvb4yrJ3jXH0ZUrmvHZRe6_WfXhVBtIl/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1htLd3JlEeapFVWhLbofBwn-ZRpGY5OXU/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1Axbr7aRmltYlGy0dvWdqEYX-V52WASxG/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1LDvFRPQ3MzOisst39uade4Td0_ZjHiJq/view?usp=sharing)  / [Winter '20](https://drive.google.com/file/d/1fU6MWoB7ob0EpLkWdwFzdWB5KFouOMHG/view?usp=sharing)/ [Fall '20](https://drive.google.com/file/d/1rZjrCPT1m204kABFRQ7imS9RN8i6Zd9X/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1lBQJw0r_OQ4-a32X9JQc3RonW5f6Q0Pq/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1uS_7Jbuycv9vbNe1fBIC52jDZ5H8DNoy/view?usp=sharing)/ [Fall '20](https://drive.google.com/file/d/1Un4v_R6m088FiK2r89YWmkTel-CmIIvE/view?usp=sharing)

</div>


</div>

----

<footer></footer>
