---
title: "Standard 10: Leadership and Collaboration"
output: 
  html_document: 
    theme: cerulean
    css: styles.css
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

----

The teacher seeks appropriate leadership roles and opportunities to take responsibility for student learning, to collaborate with learners, families, colleagues, other school professionals, and community members to ensure learner growth, and to advance the profession.  
 
----

### {.tabset .tabset-pills .tabset-fade}


#### Performance 10.1

<div style="padding-left:1px;">

Candidates engage in and reflect on different experiences related to ELA.

##### Evidence 1: Observations (1-5) (ENG 329/430)

<div style="padding-left:40px;">

**Prompt**

Below are the topics discussed in our PLC lab on September 23. You will choose one topic to observe at each of your first five observations; you will choose a different topic at each new observation. As you type each observation, you will need to do the following: write ½ a page on what you learned in your Lab PLC group concerning the topic, observe how the class and teacher address the topic (use the questions in the parentheses to help guide you), write the rest of your paper on your observations.

1. How can an ELA teacher be a leader and collaborator at the school and within the community? (Ask the teacher what he or she has done to be a leader and collaborator in the school and community. Take notes of specific advice and experiences.)—Standard 10A


**Samples**: 

1.Excellent performance: [Fall '19](https://drive.google.com/file/d/1u6SH-uAoZl0SE4UW3eQEGv2RJSB-IuWF/view?usp=sharing)/ [Winter '20](https://drive.google.com/file/d/1HkgEV3TyGGzgjpytm48daDOMCBCd1JOc/view?usp=sharing).

2.Average performance: [Fall '19](https://drive.google.com/file/d/1w2N1Gy1uwcd6PnmJ9EA1RzwKXl63z5Ka/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1-4-8nlhrJk897wgxQ1Fmrny884cTGQ3g/view?usp=sharing).

3.Poor Performance: [Fall '19](https://drive.google.com/file/d/1aJL3iL1gAzO50m7kTVi8Zg_6266PtjGT/view?usp=sharing)/ [Winter '20](https://drive.google.com/file/d/1fEMaIHU1GsK1vEh7YkbegobZslAvhEtG/view?usp=sharing). 


</div>

##### Evidence 2:Reflection (Practicum) (ENG 329)
<div style="padding-left:40px;">
**Prompt**

After you have completed the practicum, you will need to submit a reflection. It needs to be two to three pages in length, typed, MLA formatted. Please address these questions in your reflection:

1. In what ways did you collaborate with your mentor teacher or others in the learning community to help learners grow or advance your own teaching practices? Be specific. (Standard 10A)


**Samples**: 

1.Excellent performance: [Fall '19](https://drive.google.com/file/d/1X8KTrwhIskFwRn0WAk7JoqYqP_aBclSr/view?usp=sharing)/ [Winter '20](https://drive.google.com/file/d/14vb80kTNyAmBeb2mGwEgb-1CBBycR4kO/view?usp=sharing).

2.Average performance: [Fall '19](https://drive.google.com/file/d/14gyAGFNLanQNagH-2OWNnzEjtivciYVB/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1NSZkCFbrOzd7l7vQsW-1VUH810588yQI/view?usp=sharing).

3.Poor Performance: [Fall '19](https://drive.google.com/file/d/1kiLTuLMDa8faTM4Hyb0okcJt0QXqNcCr/view?usp=sharing)/ [Winter '20](https://drive.google.com/file/d/1pD5gzLX_puBlrA6-XeIo1UOceiPaZqhB/view?usp=sharing). 


</div>


##### Evidence 3: Observations (6-10) (329/430)
<div style="padding-left:40px;">

**Prompt**
This observation’s directions and chart come directly from “Bringing Reality to Classroom Management in Teacher Education” by Gordon Eisenman, Susan Edwards, and Carey Anne Cushman—Georgia Regents University).

For one hour, select one student to observe. Briefly describe what the student is doing at five-minute intervals. Would you consider this on-task or off-task behavior (engaged in activity that leads to learning)? What precipitated each positive or negative event?—Standards 3A and 10A.

After completing the observation, look at your data. Now do two things with this data:

Analyze what the data is telling you. (Are there any patterns you notice?)
Discuss what you have learned from your observation and analysis.

**Samples**: 

1.Excellent performance: [Fall '19](https://drive.google.com/file/d/1_39dP6YAM5lfu53M766grzrNJ-3LeuTW/view?usp=sharing)/ [Winter '20](https://drive.google.com/file/d/1_39dP6YAM5lfu53M766grzrNJ-3LeuTW/view?usp=sharing).

2.Average performance: [Fall '19](https://drive.google.com/file/d/1V3q-N2qvy9iHDYVm6oIHOznrXi0LrUSG/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1797-GeWAjSg815vNsS_IB1GSOGSkP9ut/view?usp=sharing).

3.Poor Performance: [Fall '19](https://drive.google.com/file/d/1aavoJ_JYYR2L6oAoofY0LhU7AD4hWymG/view?usp=sharing)/ [Winter '20](https://drive.google.com/file/d/1t15VEN2cBp77OPmmPLIyXRwzgRtjNaA7/view?usp=sharing). 


</div>


</div>

----

<footer></footer>