---
title: "Standard 2: Learning Difference"
output: 
  html_document: 
    theme: cerulean
    css: styles.css
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

----

The teacher uses understanding of individual differences and diverse cultures and communities to ensure inclusive learning environments that enable each learner to meet high standards.

----

### {.tabset .tabset-pills .tabset-fade}


#### Performance 2.1

<div style="padding-left:1px;">

Candidates implement instruction responsive to students' individual identities.


##### Evidence 1: Annotated Bibliography Lab (ENG 329)

<div style="padding-left:40px;">

**Prompt**

You will sign up for one of the following topics:

1.	Social justice—what is it? How does it connect to the ELA classroom?—Standard 5B
2.	How do language and dialect affect literacy?—Standards 2A and 3A


Find at least three scholarly journal articles on that topic and compile the information into an annotated bibliography. Use MLA formatting for citation purposes. OWL@Purdue.edu will help you organize your annotated bibliography. (45 points for bibliography, 15 points for discussion, 60 total)

**Samples**:

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1C20BFY97qLt1DwKCUjc4xhvFHdzXZ-vO/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1Fz0vJseigakEzuHv-qp7WiegFp6cbmZo/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/13VZLyMig1PvFeVyamKfc7gy3mi9o3Qn-/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/13I6TK57Qefvd-ok2F76hDai66Ke3augw/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1tkEsRhyizYBScIrMJPQc3kjotTL0x334/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/13VZLyMig1PvFeVyamKfc7gy3mi9o3Qn-/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1G84mOFKFVuzOW7pgDjmMW_bv8RtDpoEq/view?usp=sharing)/ [Winter '20](https://drive.google.com/file/d/1W9GplP3c70V4Kxms-qNIRBRuRV8_i35Q/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1zbvvvr4qqfY0BDEdt9e-KLRZLHJuXb58/view?usp=sharing)
</div>

##### Evidence 2: Writing Sequences (ENG 329)
<div style="padding-left:40px;">
**Prompt**

This assignment is lesson planning to teach four genres of writing: fiction, personal narrative, argumentation, and research.  You will plan through five stages, which roughly correspond to pre-writing, writing, editing/evaluation. This will happen in five stages. A sample of this assignment will be provided.

**Samples**: 

1. Excellent performance:  [Fall '19](https://drive.google.com/file/d/14c-s3xbLpPA5GmTEN6by0G7BSe18HE3P/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1ZkdTqUm_k6N3Uq2QtqWo3mNrhPdECVP1/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/164snfLPRmVCQMbRLCWlF2xPX9ahTLw3f/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/17pDWqY7JhXYMGLn_3AsjOaAbq3gZvLbv/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/13kLVUok2JNPxOQon43RJN_5W9mYZGq5b/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1U-7cM_ocCY7GdObsWSbIGkppsgxeb0Z4/view?usp=sharing)

3.  Poor performance: [Fall '19](https://drive.google.com/file/d/1dqjt2gg9v0hybme0MM1qyEYnPlZZ-8_T/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/14Xf-T9mwMUYTRy00l-hR_wAE-KqGKMqo/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1ajT_V8JR9kezP14VQHvnOy9uw4zOAc7w/view?usp=sharing)

</div>


##### Evidence 3: Literature Circles ~ Sociological role (ENG 356)
<div style="padding-left:40px;">
**Prompt**

Actively participate in novel discussions by completing your assigned group role and speaking in your group discussions. Discussion will take place in class.

1. *Role: Sociological Lens*: The point of this role is to explore the role of power in a society. Many today are discussing social justice themes—this is an opportunity for you to be aware and join the conversation on this topic by exploring power within the context of literature. 
2. *Role: Social Justice Lens*: Publishers, editors, writers, and teachers work together when it comes to using Young Adult Literature in a classroom. Any of these groups of people post teaching ideas online.  For this literature circle role, you will create a lesson plan that focuses on a social justice theme. 

**Samples**: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1Cg2qMwNqeTX13pNrPieiJXIkdCOQOIb0/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1bzUwURqZ9euRKrbW524jtJbsi_5MZsow/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1vJ_KmIGflC8G_f7upFbeIUVveQqQjutK/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1-tAnXAd4FvG_2aPo4j7Px8br-6-9fmY4/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1LG19u0k_wygKTbc6Uxn60Uumb50pjQ_Q/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1yspuylfT4kShdCiZ6qotBR3c-iSO51tc/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1Hh9M080qEOybnahkxI2JLnwJ1ftA1jxO/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1s94HVIzWj_Cksxz-Pj9hHXXZgrPsaLd8/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1YzSc5KO0yHgE7sGzhk_4TVR7tByl1Htd/view?usp=sharing)

</div>


</div>

----


#### Performance 2.2

<div style="padding-left:1px;">
Candidates design and/or implement instruction that incorporates students’ linguistic and cultural backgrounds.
 
 

##### Evidence 1: Book Pusher (ENG 356)

<div style="padding-left:40px;">
**Prompt**

You must show your professor that the books you chose will really work for those tough people in those three groups. You will come to Sister Glenn’s office (Rigby 304) or Sara’s office (Rigby 101) on your scheduled test day and time. You will come in, sit down, and roll the die. The number you roll, will indicate which group (1 and 4=young adult, 2 and 5=parent, and 3 and 6=future 356 class) and which three of the nine books you will discuss. After the roll of the die, you will have 10 minutes to talk. You must address these three things in your spiel:

A) Tell Sara or me about the person you are targeting. Be specific so we have a good idea of who this individual is (2 minutes).
B) You must then make your three book recommendations and explain why those are the best choices for the individual you just described (5-6 minutes).
C) At the end, you will discuss some of your findings from your personal reflection (1-2 minutes). 

NOTE: The propmt for this assignment changed during the Fall 2020 semester. It can be found [here](https://drive.google.com/file/d/1INLDbHefInmVvrbJySDHju6kBc7qISlr/view?usp=sharing).

**Samples**:

A graphical summary of the final grades can be found here: [Fall '19](https://drive.google.com/file/d/1ROFENwvrK2yEhxV6PBFkU7Xk6S-mq-aF/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1zcL25hB-eOFX2v1jauat6HBhcrV8qs3W/view?usp=sharing) / [Fall '20](https://docs.google.com/document/d/1nu5Wwg_Xgr9X71_qDl1Yt_nV546NNcu22l-MFUWUhIM/edit?usp=sharing)

</div>

##### Evidence 2: Literature Circles ~ LitLinks role (ENG 356)
<div style="padding-left:40px;">
**Prompt**

Publishers, editors, writers, and teachers work together when it comes to using Young Adult Literature in a classroom. Any of these groups of  people post teaching ideas online.  For this literature circle role, you will create a document that gives links and advice on teaching a Young Adult novel. 

Parts of the LitLinks:

1.	Title and Summary. Please provide a brief summary of the text. -3 points
2.	Links to sites about two different themes in the book. Please provide a description of the links. If possible, provide modern day connections. –10 points
3.	Links to at least two teaching ideas. Please provide a description of the links. Choose activities that would serve a diverse group. –12 points

**Samples**:

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1vsU6LV1xoRqCD-rE-eS0lQIT02w67gX6/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1Yawq5PqjscSCQaU16jXqCLvYZaohNzcK/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/12fYlLrJ4-2FTNh1MMXDIz4CR6-THwirn/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1pZbtcAj85PTEt-XA4InYzVupzMEQDItn/view?usp=sharing)  / [Winter '20](https://drive.google.com/file/d/1FMncORFpmEH6pDzxbUMxcxCjI3uZkyUJ/view?usp=sharing)/ [Fall '20](https://drive.google.com/file/d/18reC5uGSOExvvIBoUpcebajIN1LQo5nr/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1eYqYIrtLYLpfxvu_qJcchiRELGZvIdY3/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1SCmqaSPVEvI8dUBSa0KIJMYgYRglssKV/view?usp=sharing)/ [Fall '20](https://drive.google.com/file/d/1iBiv6rywfTjnGF6n6bahqSxtUUH-BUK4/view?usp=sharing)
</div>


##### Evidence 3: Writing Sequences (ENG 329)
<div style="padding-left:40px;">

**Prompt**

This assignment is lesson planning to teach four genres of writing: fiction, personal narrative, argumentation, and research.  You will plan through five stages, which roughly correspond to pre-writing, writing, editing/evaluation. This will happen in five stages. A sample of this assignment will be provided.

**Samples**: 

1. Excellent performance:  [Fall '19](https://drive.google.com/file/d/14c-s3xbLpPA5GmTEN6by0G7BSe18HE3P/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1ZkdTqUm_k6N3Uq2QtqWo3mNrhPdECVP1/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/164snfLPRmVCQMbRLCWlF2xPX9ahTLw3f/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/17pDWqY7JhXYMGLn_3AsjOaAbq3gZvLbv/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/13kLVUok2JNPxOQon43RJN_5W9mYZGq5b/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1U-7cM_ocCY7GdObsWSbIGkppsgxeb0Z4/view?usp=sharing)

3.  Poor performance: [Fall '19](https://drive.google.com/file/d/1dqjt2gg9v0hybme0MM1qyEYnPlZZ-8_T/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/14Xf-T9mwMUYTRy00l-hR_wAE-KqGKMqo/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1ajT_V8JR9kezP14VQHvnOy9uw4zOAc7w/view?usp=sharing)


</div>


</div>

----

<footer></footer>