---
title: "Standard 6: Assessment"
output: 
  html_document: 
    theme: cerulean
    css: styles.css
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

----

The teacher understands and uses multiple methods of assessment to engage learners in their own growth, to monitor learner progress, and to guide the teacher’s and learner’s decision making. 

----

### {.tabset .tabset-pills .tabset-fade}


#### Performance 6.1

<div style="padding-left:1px;">

Candidates design a range of authentic assessments of reading and literature.  **Rationale can be found** [**here**](https://drive.google.com/file/d/1sDvY-6jBEp8Raesi9gyEwYrqzU_hJZP_/view?usp=sharing)


##### Evidence 1: Lexile Level Text Set (ENG 356)

<div style="padding-left:40px;">

*Prompt*
Students go over this [PowerPoint](https://drive.google.com/file/d/1LeFBgGGW6knfMqZHHZxN3FWgVYuRnxpN/view?usp=sharing) with the professor; then they complete the following assingment: 


1. As you complete Goodreads, look up and **record the Lexile level** of each book.

2. As you complete the 25 books, imagine recommending a series of five books to a specific student. **Determine the grade level** and gender of the imagined student you want to write your text set for. Then, choose five books **that increase in Lexile level** and which are connected thematically in a way that would make sense reading them in the order you recommend.

3. List the five books and their Lexile level. For each book, give a rationale for why you would recommend that book for that student.

*Samples*: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1ro2sNhvP2hGqJBYoAH7wgWbUDz6r8q4j/view?usp=sharing) / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/1SqvwBMFGT5uaUbUUNVFng2h2ZPGqbERv/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1J4IbAS-aVdIqMVrnkw_IlEsQUeE-FU7J/view?usp=sharing) / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/1pmjKpD-8pnRmtzt8oxBqzGDG7vgXBPkJ/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1vTpZF6CphuLMciTpPNlPSlcR4G7hSHag/view?usp=sharing) / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/1RdsqzH3ku6HC3igKSmbypu40KYrqWUVM/view?usp=sharing) 



</div>

##### Evidence 2: Mini-Lesson (ENG 329)
<div style="padding-left:40px;">

*Prompt*

You will teach a minimum of three times. You can work this out with your mentor teacher. This may be for a full or partial class period. Please submit **your lesson plan** to me via email three days in advance of teaching. Then, I can give you some feedback and your mentor teacher can give you some feedback. Remember, your mentor teacher is still held responsible for what you teach—please make him or her a big part of your planning process. These elements need to be in your lesson plan to receive full credit: objective, standard, **assessment**, hook, I DO, WE DO, THEY DO, closure, and enough detail that a sub could teach your lesson. You may want to ask your mentor teacher for lesson plan templates that have been helpful to him or her. (Standard 8A (Parts of 4 and 5—depending on the lesson)).

*Samples*: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1hq0jgWQXLTGUdGo5Kn2a1zb1UtkTn8OL/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/15hrMLTMDxyWE2sIRGdMCEArfjz3ByHQ1/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1DnIobKodZ9VHeNltCCFSYIJo-WRncs_e/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1E-72WZSrIm-Kuxn-uREhDP7vRf7mTqfW/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1uvP5kLK-PX-gKIKql9zU4rfiicTpHRP_/view?usp=sharing)  / [Fall '20](https://drive.google.com/file/d/1DqCjgS0zUMv1JmFQ9ae9-4GXz81orMPx/view?usp=sharing)

3. Poor Performance: [Fall '19](https://docs.google.com/document/d/1jirqTAVjW-e_D3vJJbWWX2PTgGAqbuyGUMgLS8JU_OE/edit?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1TCFLwEYfjZxo6ym5NjegD7hnBIvJGqMj/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1m9hJzsVPQnPHqGww704n-4aDy5jNmdTf/view?usp=sharing) 


</div>


##### Evidence 3: Literature Circles ~ LitLinks Role (ENG 356)
<div style="padding-left:40px;">
*Prompt*

Publishers, editors, writers, and teachers work together when it comes to using Young Adult Literature in a classroom. Any of these groups of  people post teaching ideas online.  For this literature circle role, you will create a document that gives links and advice on teaching a Young Adult novel. 

Parts of the LitLinks:

1.	Title and Summary. Please provide a brief summary of the text. -3 points
2.	Links to sites about two different themes in the book. Please provide a description of the links. If possible, provide modern day connections. –10 points
3.	Links to **at least two teaching ideas**. Please provide a description of the links. **Choose activities that would serve a diverse group.** –12 points


*Samples*:

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1l7xkubBL34FLIi6sHHLmi75wNfQcCjB8/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1xXEL272WOL1ancbRgiTXY3gUuZc4AuZv/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1Lhph5IpwnipNQoM0sD5BcU3BioO_r7eD/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1J4sgxd046bmdZXIe5EWoh6v_NbRkyTnA/view?usp=sharing)  / [Winter '20](https://drive.google.com/file/d/131Evc0ed5qSIwxDueLnbGdEfxpMDItVb/view?usp=sharing)/ [Fall '20](https://drive.google.com/file/d/1c27pZG6l_370UgNacthbe5rYw9Dzphzr/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1SSObdsoTPQ_EWOraR4k55vJGNOIAUt92/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1eFcADkSHCVozUzPNdPQVMeLv0G5JcQ92/view?usp=sharing)/ [Fall '20](https://drive.google.com/file/d/1amklYJBo6tGOrC_IwzpJxlIxqkTbXd_G/view?usp=sharing)

</div>


</div>

----


#### Performance 6.2

<div style="padding-left:1px;">

Candidates select appropriate reading assessments in response to student interests. **Rationale can be found** [**here**](https://drive.google.com/file/d/1eprCxapizbD9Jk5A8uhtffbkRmGj7b5b/view?usp=sharing) 
 
##### Evidence 1: Annotated Bibliography (ENG 329)

<div style="padding-left:40px;">

*Prompt*
You will sign up for one of the following topics:

1. What are the best practices (strategies/activities) **in assessments for ELA?**—Standard 6B.

Find at least three scholarly journal articles on that topic and compile the information into an annotated bibliography. Use MLA formatting for citation purposes. OWL@Purdue.edu will help you organize your annotated bibliography. (45 points for bibliography, 15 points for discussion, 60 total)

*Samples*:

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1qkLZwgf84qcCYVqMPwVozjJJGz5zHIGF/view?usp=sharing) / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/1ekM0oPfwNK7yHVCnhdAjgTiik4xXLI97/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1qim-OrzV42qRTGMX9visuDDj8KuJv54b/view?usp=sharing) / Winter '20 (excused ~ covid-19) / Fall '20 (none)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1tkdds33KrWzK4uiEhNYOtVdK0zeCOFLH/view?usp=sharing) / Winter '20 (excused ~ covid-19) / Fall '20 (none)


</div>

##### Evidence 2: Syllabus (ED 461)
<div style="padding-left:40px;">

The Syllabus for **Reading in the Content Area** (ED 461) can be found here [Fall '19/ Winter '20](https://drive.google.com/file/d/1jJU1nYrYvRFpQZvDYC9MiBP6MHy57-3O/view?usp=sharing) / [Fall '20](https://docs.google.com/document/d/1M1mcKEBccIfZvo63XAeUY44fwKdyf9OySIjYVUPfbL4/edit?usp=sharing)

</div>


##### Evidence 3: Book Pusher (ENG 356)
<div style="padding-left:40px;">

*Prompt*

You must your professor that the books you chose will really work for those tough people in those three groups. You will come to Sister Glenn’s office (Rigby 304) or Sara’s office (Rigby 101) on your scheduled test day and time. You will come in, sit down, and roll the die. The number you roll, will indicate which group (1 and 4=young adult, 2 and 5=parent, and 3 and 6=future 356 class) and which three of the nine books you will discuss. After the roll of the die, you will have 10 minutes to talk. You must address these three things in your spiel:

A) Tell Sara or me about the person you are targeting. Be specific so we have a good idea of who this individual is (2 minutes).
B) You must then make your three book recommendations and explain why those are the best choices for the individual you just described (5-6 minutes).
C) At the end, you will discuss some of your findings from your personal reflection (1-2 minutes). 

*Samples*:

A graphical summary of the final grades can be found here: [Fall '19](https://drive.google.com/file/d/1ROFENwvrK2yEhxV6PBFkU7Xk6S-mq-aF/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1zcL25hB-eOFX2v1jauat6HBhcrV8qs3W/view?usp=sharing) / Fall '20 ( [final grades](https://docs.google.com/document/d/1nu5Wwg_Xgr9X71_qDl1Yt_nV546NNcu22l-MFUWUhIM/edit?usp=sharing), [excellent](https://drive.google.com/file/d/1RnOFeVEXZ5FUNGUy26noABL7tczYon5Y/view?usp=sharing), [average](https://drive.google.com/file/d/1JVEc5bYmA6gISUny2pj_cRRueMle5JQa/view?usp=sharing), [poor](https://drive.google.com/file/d/1ICUZ4VXe2ilX00ZXHTbI_YhG73ECgeUg/view?usp=sharing) )


</div>


</div>


----



#### Performance 6.3

<div style="padding-left:1px;">
Candidates select a range of assessments for sutdents that promote their development as writers. **Rationale can be found** [**here**](https://drive.google.com/file/d/1UA_40RKjX8VLqp1OhUXdgV-kdhlFxoFx/view?usp=sharing)
 
##### Evidence 1: Writing Sequences (ENG 329)

<div style="padding-left:40px;">
*Prompt*

This assignment is **lesson planning to teach four genres of writing**: fiction, personal narrative, argumentation, and research.  You will plan through five stages, which roughly correspond to pre-writing, writing, editing/evaluation. This will happen in five stages. A sample of this assignment will be provided.

*Samples*: 

1. Excellent performance:  [Fall '19](https://drive.google.com/file/d/1HGjq34-zv1HEM5ZzO3m7-BMELzFqHdME/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1YMHkUvX5pdBoehddcIWmgUMo24GFmUR5/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1VwtOuqQd4xCSixhStbyshMjYkOj91IR5/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1JnkQ8CYh9DHiuvsISjG02lviCexB73nE/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/17A_33ixFcvgdmMquGlsKJbuEgrnTOxw_/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1ePlWjeN0mw1fePqEAJHZuHMA1uNNjdKt/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/15x8rvYWtV6IhxMmIZzG3KaGfa3zMuF6A/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1Fm7U99OciFa6IIzmFwpemEPmUWdN9OgO/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1R4AxyjXCJDL0d9p8T8hkfdr-VDQdlKyg/view?usp=sharing)

</div>

##### Evidence 2: Grading Packet (ENG 329)
<div style="padding-left:40px;">
*Prompt*

There are twelve student papers in the portfolio. For each paper do the following:

1. Read completely before marking anything.
2. Read again, making marginal comments that focus on the Transparent Reader/Advice Giver role.
3. Mark any spelling, grammar, or punctuation errors that you feel should be emphasized.  Remember that you don’t need to mark every mistake, but you should **look for patterns and point out where they may be misunderstanding a concept.** 
4. **Make a summative end comment on the paper itself**. Offer suggestions for revision. Compliment them on what they are doing well.
5. **Fill out a rubric for each paper**, ranking them from 1-5 on the different elements listed. 


*Samples*: 

1. Excellent performance:  Fall '19 (student submitted paper copy of this assignment) / [Winter '20](https://drive.google.com/file/d/1srzaqpyy-seJM_S9kbugRash1og2Zbb8/view?usp=sharing)

2. Average performance: Fall '19 (student submitted paper copy of this assignment) / Winter '20 (not available: all students did well except for one---see sample below)

3. Poor performance: Fall '19 (student submitted paper copy of this assignment) / [Winter '20](https://drive.google.com/file/d/19u_daLk9h_ImJMtg3Ly2N-qADEdGMWTF/view?usp=sharing)

</div>


##### Evidence 3: Syllabus (ENG 329)
<div style="padding-left:40px;">

The syllabus for Teaching Writing in Secondary Schools (ENG 329) can be found here:  [Fall '19](https://drive.google.com/file/d/1e-1qbdwGxYMCaRPbk6JVTofBFhxvJKU1/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1e-1qbdwGxYMCaRPbk6JVTofBFhxvJKU1/view?usp=sharing) / [Fall '20](https://docs.google.com/document/d/1b8_FmlcZBmPWmlVDLxIJS0V9z1m9sl0uJq6iDoyWiE0/edit?usp=sharing)

</div>


</div>

----

#### Performance 6.4
<div style="padding-left:1px;">

Candidates differentiates instruction based on multiple kinds of assessments.  **Rationale can be found** [**here**](https://drive.google.com/file/d/1S4RT4cjGllugN3N_njuSFd7y9zmg1CiN/view?usp=sharing)
 
##### Evidence 1: Grading Packet (ENG 329)

<div style="padding-left:40px;">

*Prompt*

There are twelve student papers in the portfolio. For each paper do the following:

1. Read completely before marking anything.
2. Read again, making marginal comments that focus on the Transparent Reader/Advice Giver role.
3. Mark any spelling, grammar, or punctuation errors that you feel should be emphasized.  Remember that you don’t need to mark every mistake, but you should **look for patterns and point out where they may be misunderstanding a concept.** 
4. **Make a summative end comment on the paper itself.** Offer suggestions for revision. Compliment them on what they are doing well. 
5. **Fill out a rubric for each paper**, ranking them from 1-5 on the different elements listed. 


*Samples*: 

1. Excellent performance:  Fall '19 (student submitted paper copy of this assignment) / [Winter '20](https://drive.google.com/file/d/1srzaqpyy-seJM_S9kbugRash1og2Zbb8/view?usp=sharing) / Fall '20 (not used)

2. Average performance: Fall '19 (student submitted paper copy of this assignment) / Winter '20 (student submitted paper copy of this assignment) / Fall '20 (not used)

3. Poor performance: Fall '19 (student submitted paper copy of this assignment) / [Winter '20](https://drive.google.com/file/d/19u_daLk9h_ImJMtg3Ly2N-qADEdGMWTF/view?usp=sharing) / Fall '20 (not used)
</div>

##### Evidence 2: Writing Sequences (ENG 329)
<div style="padding-left:40px;">
*Prompt*

This assignment is **lesson planning to teach four genres of writing**: fiction, personal narrative, argumentation, and research.  You will plan through five stages, which roughly correspond to pre-writing, writing, editing/evaluation. This will happen in five stages. A sample of this assignment will be provided.

*Samples*: 

1. Excellent performance:  [Fall '19](https://drive.google.com/file/d/1HGjq34-zv1HEM5ZzO3m7-BMELzFqHdME/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1YMHkUvX5pdBoehddcIWmgUMo24GFmUR5/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1VwtOuqQd4xCSixhStbyshMjYkOj91IR5/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1JnkQ8CYh9DHiuvsISjG02lviCexB73nE/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/17A_33ixFcvgdmMquGlsKJbuEgrnTOxw_/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1ePlWjeN0mw1fePqEAJHZuHMA1uNNjdKt/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/15x8rvYWtV6IhxMmIZzG3KaGfa3zMuF6A/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1Fm7U99OciFa6IIzmFwpemEPmUWdN9OgO/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1R4AxyjXCJDL0d9p8T8hkfdr-VDQdlKyg/view?usp=sharing)
</div>


##### Evidence 3: Grading Writing (ENG 329)
<div style="padding-left:40px;">

Students review principles of how to grade writing more effectively as evidenced with the following material:  [Fall '19](https://drive.google.com/file/d/1o4jYuUZ1v0T3Qdp_t9ZSPJVX7vZzPtYu/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1hHGg6N6ABgmn3y0sfsipchvE3vDspR0t/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1C7paW4DEOCs-MCdkVk9UA9mLH9W4b8LY/view?usp=sharing)

</div>


</div>

----

<footer></footer>