---
title: "Standard 4: Content Knowledge"
output: 
  html_document: 
    theme: cerulean
    css: styles.css
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

----

The teacher understands the central concepts, tools of inquiry, and structures of the discipline(s) he or she teaches and creates learning experiences that make the discipline accessible and meaningful for learners to assure mastery of the content. 

----

### {.tabset .tabset-pills .tabset-fade}


#### Performance 4.1

<div style="padding-left:1px;">

Candidates use literary theories to interpret and critique a range of texts. **Rationale can be found** [**here**](https://drive.google.com/file/d/12VoXvQ5Z3wz5QYfyohA-LIxIdUSvuHVs/view?usp=sharing)


##### Evidence 1: Paper work of literature and its historical context (ENG 331-336)

<div style="padding-left:40px;">

*Summary*

Students are required to take a series of literature courses (ENG 331-336) where **they analyze pieces of literature** and their historical texts. Here are different documents which evidence some of the work they do: 

*Syllabus*: a copy of the syllabus can be found here: [Fall '19](https://docs.google.com/document/d/1H7OhDlDaH6D9rCDB-5rYVcqKN7RBkyRfmaN4qv_YitU/edit?usp=sharing) / [Winter '20](https://docs.google.com/document/d/1WcYuuH8wJU5GNS4LLOX5G79dBCr__tDDEj2IntDrNJo/edit?usp=sharing) / [Fall '20](https://docs.google.com/document/d/13Q0Ro8P2qbMwT9UDuZRKb9em1oDXcEk4tmx2flLNSJQ/edit?usp=sharing)

*Midterm (ENG 336)*: a copy of the midterm can be found here: [Fall '19](https://docs.google.com/document/d/19-WClw0kGEW1NBo8YnIE9KNOm6FC4ULxdVtJrpAQDCQ/edit?usp=sharing)/ [Winter '20](https://docs.google.com/document/d/1DPIC3BPeyTvI9uUgZFLl6UJaji1yKSxfx_b8y7P_WfI/edit?usp=sharing)

*Quiz*: a copy of a quiz can be found here: [Fall '19](https://drive.google.com/file/d/1a4ZuxXL5h8JQlYXfl9_a5GKkS9xpCpgN/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1DoyxEP-xGhFFOZhj65jCOawyz2KWYvrN/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1ifqSdcRu7cdoiFZIYBna2BDhNmtp_V0K/view?usp=sharing)

*Schedule (ENG 336)*: a copy of the schedule can be found here: [Fall '19] (not available) / [Winter '20](https://drive.google.com/file/d/1QT7W_e8Hp3xbJeve1XyAc76INPpoSyVL/view?usp=sharing) / [Winter' 20 post-covid](https://drive.google.com/file/d/1-TNCpRWLoH_IYKarN3XA9i7tolTpWg2y/view?usp=sharing)

*Research paper (ENG 335)*: a copy of the prompt can be found here: [Winter '20](https://drive.google.com/file/d/1B4omAO-_GYrzBPcjDmPk0SAAOUJwaJnt/view?usp=sharing) / Fall '20 ( [prompt](https://drive.google.com/file/d/1su97a19GEaAl_rfvtki3hOPIBplCMxW3/view?usp=sharing), [excellent](https://drive.google.com/file/d/1LYDeivMvaZvNDjvo0_l0-siEnUHhQwnP/view?usp=sharing), [poor]() )
</div>

##### Evidence 2: Literature Circles - Historical Lens (ENG 356)

<div style="padding-left:40px;">

*Prompt*

Actively participate in novel discussions by completing your assigned group role and speaking in your group discussions. Discussion will take place in class.

1. *Role: Historical Lens*: For this role, you will need to do some historical research to help yourself and your group better **understand the context of an item**, character, or event within the text. In column one, choose one item, character, or event that may have historical significance to the text itself. For column two, do some research on that chosen character, event, etc. Summarize your research. Make sure to cite your source. **Explain how your research connects to the item in the book and helps you better understand** the context of the story. 

*Samples*: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1oMGclcD58AC7Peif_A805_oHiXYLvjrH/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1pQusJnscCl70hzRTS2tWlIYV_OYpJYur/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1c1etoBr5Xam4DrDkQVvCYy5NlHbRhBjR/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1IlsU508OQFjHQ7hSbB1yQ5VjdMDv1DMh/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1aL3CnZIyDPTjDS9NK4jSka_Z2PfYUpts/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1iKdnc5Ho8DZ_EgD4u7uoN53putPwzdaW/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1-p81jtrzU4e3fO87kV4EV8RxjAQ31Ftf/view?usp=sharing)/ [Winter '20](https://drive.google.com/file/d/1ayoT5ipJbw9g-qBYPC7T5IL06xmqUcOg/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/10umgGxEaHQ_YAbqv335s2fnInDcABZ3f/view?usp=sharing)

</div>


##### Evidence 3: Goodreads (ENG 356)
<div style="padding-left:40px;">

*Prompt*

This semester you will read 20 YA books.Many of these are not difficult to read, but it is essential that you keep up with both the reading and the assignments.  In order to stay on top of things, plan to read two books per week. That pace should keep you from grief at the end of the semester. (10 points per book, 200 total/20 points for the Reading Record) 

20 books:

A)	8 class assigned books  (the 9th  and 10th will be books of your choice in connection to our multicultural book studies)
B)	1 book from Honor List (or other award winner)—please mark on reading record
C)	8 books your choice—various genres, time periods—please mark on reading record
D)	1 censored book (in addition to I am the Cheese)—please mark on reading record

NOTE: Please do not read books in which you have already read or seen the movie (Harry Potter series, Hunger Games series, The Giver quartet, Maze Runner series, Twilight Series, etc.). Where you are already familiar with these books/movies, do yourself a favor and branch out—read something new. This will benefit you in the end. 


*Samples*:

1. Excellent Performance: [Fall '19](https://drive.google.com/file/d/11EyhY7rlncf0dd9XsPhbsuulbr69Z4qN/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1e9pKR34LAMslVFGbrnDVuUnB9SWprMgD/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/19cOmMsUNOl2XSwe4-YsrSWvwqK5l6MHo/view?usp=sharing)

2. Average Performance: [Fall '19](https://drive.google.com/file/d/1dLTFE-ZlbXpyJd1iWQNHcEDaUZySVmO4/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1sZ8taeZt07WJMXmZCp6stp7rJYxUQagW/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1X3GlRNfNFFN_pC7ozVmrGUZHC3yLxywa/view?usp=sharing)

3. Poor Performance: [Fall '19](https://drive.google.com/file/d/1zR9uXF6mogOPE6FIGjvyQ1XZRXEX5UdM/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1BEnZsD2lapf2yH6VNZhO1pAQ0cy1r5jZ/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1SCmRfCpgeP7jx5CkzMs0nn_YGzuCgt1O/view?usp=sharing)

</div>


</div>

----

#### Performance 4.2
<div style="padding-left:1px;">

Candidates use the conventions of English language as they relate to various rethorical situations.**Rationale can be found** [**here**](https://drive.google.com/file/d/1aqOw8GQgqb89d4sYmedcgjnt1eJRfWY9/view?usp=sharing)
 
##### Evidence 1: Literary Analysis Paper (ENG 314)

<div style="padding-left:40px;">

*Prompt*

Write about a prompted **writing assignment** you had to complete as a test during high school. How was the writing process? How did your writing turn out? Did you feel connected to the assignment?

Note: the grading criteria used during Fall 2020 can be found [**here**](https://docs.google.com/document/d/1trKkD5CWBexkfpEqiXYGwhMFfvpZJ_a6XAHPCwPp1rU/edit?usp=sharing).

*Samples*:

1. Excellent Performance: [Fall '19](https://drive.google.com/file/d/1aLKu_UrBZSaUxOFkjU5b0_b9TqZQRoHH/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1SdTViKdJacYlvz6YXknegSbCFZI_kqds/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/164koQfEhzbVxaQcFIUlTOV56UkpEFNfI/view?usp=sharing)

2. Average Performance: [Fall '19](https://drive.google.com/file/d/1ClSjONNx-c5nCdVYnIn9QAK3Sm4BbWdj/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1tzcSHYKQ4NVeSljlI2lYW4uLhpSMH5vY/view?usp=sharing) / Fall '20 (none)

3. Poor Performance: [Fall '19](https://drive.google.com/file/d/1JMZDvzPgGbCkMbBQ4Ht2iTpoJyLDCiFd/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1xIIMz34Jk5fl-RJ5KwqBdL9e9E5f37mw/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1E37a8REOw3OvWemuNlFikoAPi-qHYHGd/view?usp=sharing)

</div>

##### Evidence 2: Syllabus (ENG 314)
<div style="padding-left:40px;">

The Syllabus for Advanced Research and Literary Analysis (ENG 314) can be found here: [Fall '19](https://docs.google.com/document/d/1LIdkQ_ne0Jo9pJj1_K11CsVpj8B4BGXsH2TsDq8wLuY/edit?usp=sharing) / [Winter '20](https://docs.google.com/document/d/193j0IZYtjp2kWS8xdz1miXSEScVYmA5w1YzpsXLj4ss/edit?usp=sharing) / Fall '20 ( [course outline](https://docs.google.com/document/d/18JMRBXu7NYH7bsqKmFItz2R12toKezy2vEVdYCC6paM/edit?usp=sharing), [syllabus '20](https://docs.google.com/document/d/1fURSN8c0mMHg_P7dklbu04OmkBuJavLw94-xBvWidVE/edit?usp=sharing), [quiz](https://drive.google.com/file/d/1afgEcFvifBw-0c7ZipdWyD-YX0bfYx85/view?usp=sharing))

</div>

##### Evidence 3: Syllabus (ENG 325)
<div style="padding-left:40px;">

The Syllabus for Language Theory - Grammar and Usage (ENG 325) can be found here: [Fall '19](https://docs.google.com/document/d/1PQm5PirllggH8XFVhG9b7vth5NMumjSABUbYj2O2v1w/edit?usp=sharing) / [Winter '20](https://docs.google.com/document/d/1PQm5PirllggH8XFVhG9b7vth5NMumjSABUbYj2O2v1w/edit?usp=sharing) / Fall '20 ( [syllabus](https://drive.google.com/file/d/1y4459C_sR15GgU981iMKKpd2U80V4Eiv/view?usp=sharing), [course outline](https://drive.google.com/file/d/1ReaxhXDtKkaGcgyFix8rmT9dJI7f-dDv/view?usp=sharing))

</div>


</div>


----


#### Performance 4.3

<div style="padding-left:1px;">

Candidates know how to compose texts. **Rationale can be found** [**here**](https://drive.google.com/file/d/1kkz4ToLdVUIY2dfYA5eVmyYmxFVsG4ej/view?usp=sharing)
 
 
##### Evidence 1: Literary Analysis Paper (ENG 314)

<div style="padding-left:40px;">
*Prompt*

**Write** about a prompted **writing assignment** you had to complete as a test during high school. How was the writing process? How did your writing turn out? Did you feel connected to the assignment?

Note: the grading criteria used during Fall 2020 can be found [here](https://drive.google.com/file/d/1o4Rkj6hCfpOx6E58NukCKWb9aMg8YoEY/view?usp=sharing).

*Samples*:

1. Excellent Performance: [Fall '19](https://drive.google.com/file/d/1aLKu_UrBZSaUxOFkjU5b0_b9TqZQRoHH/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1SdTViKdJacYlvz6YXknegSbCFZI_kqds/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/164koQfEhzbVxaQcFIUlTOV56UkpEFNfI/view?usp=sharing)

2. Average Performance: [Fall '19](https://drive.google.com/file/d/1ClSjONNx-c5nCdVYnIn9QAK3Sm4BbWdj/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1tzcSHYKQ4NVeSljlI2lYW4uLhpSMH5vY/view?usp=sharing) / Fall '20 (none)

3. Poor Performance: [Fall '19](https://drive.google.com/file/d/1JMZDvzPgGbCkMbBQ4Ht2iTpoJyLDCiFd/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1xIIMz34Jk5fl-RJ5KwqBdL9e9E5f37mw/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1E37a8REOw3OvWemuNlFikoAPi-qHYHGd/view?usp=sharing)


</div>

##### Evidence 2: Syllabus (ENG 314)
<div style="padding-left:40px;">

The Syllabus for Advanced Research and Literary Analysis (ENG 314) can be found here: [Fall '19](https://docs.google.com/document/d/1RXODZsJbXqo43_v3eA2frQUzwKGopKl2kHSl2qHADTQ/edit?usp=sharing) / [Winter '20](https://docs.google.com/document/d/1RXODZsJbXqo43_v3eA2frQUzwKGopKl2kHSl2qHADTQ/edit?usp=sharing) / Fall '20 ( [course outline](https://docs.google.com/document/d/18JMRBXu7NYH7bsqKmFItz2R12toKezy2vEVdYCC6paM/edit?usp=sharing), [syllabus '20](https://docs.google.com/document/d/1fURSN8c0mMHg_P7dklbu04OmkBuJavLw94-xBvWidVE/edit?usp=sharing), [quiz](https://drive.google.com/file/d/1afgEcFvifBw-0c7ZipdWyD-YX0bfYx85/view?usp=sharing))

</div>


##### Evidence 3: Writing Sequences (ENG 329)
<div style="padding-left:40px;">
*Prompt*

This assignment is lesson planning to **teach four genres of writing**: fiction, personal narrative, argumentation, and research.  You will plan through five stages, which roughly correspond to **pre-writing, writing, editing/evaluation**. This will happen in five stages. A sample of this assignment will be provided.

*Samples*: 

1. Excellent performance:  [Fall '19](https://drive.google.com/file/d/14c-s3xbLpPA5GmTEN6by0G7BSe18HE3P/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1ZkdTqUm_k6N3Uq2QtqWo3mNrhPdECVP1/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/164snfLPRmVCQMbRLCWlF2xPX9ahTLw3f/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/17pDWqY7JhXYMGLn_3AsjOaAbq3gZvLbv/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/13kLVUok2JNPxOQon43RJN_5W9mYZGq5b/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1U-7cM_ocCY7GdObsWSbIGkppsgxeb0Z4/view?usp=sharing)

3.  Poor performance: [Fall '19](https://drive.google.com/file/d/1dqjt2gg9v0hybme0MM1qyEYnPlZZ-8_T/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/14Xf-T9mwMUYTRy00l-hR_wAE-KqGKMqo/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1ajT_V8JR9kezP14VQHvnOy9uw4zOAc7w/view?usp=sharing)

</div>


</div>

----


#### Performance 4.4
<div style="padding-left:1px;">

Candidates know how to acquire and apply vocabulary knowledge.  **Rationale can be found** [**here**](https://drive.google.com/file/d/1whW5DTdrVA8IxLoeBrFz1Uf87t3ATkDr/view?usp=sharing)
 
##### Evidence 1: Lexile Level Text Set Assignment (ENG 356)

<div style="padding-left:40px;">

*Prompt*

1. As you complete Goodreads, look up and **record the Lexile level** of each book.

2. As you complete the 25 books, imagine recommending a series of five books to a specific student. Determine the grade level and gender of the imagined student you want to write your text set for. Then, choose five books that **increase in Lexile level** and which are connected thematically in a way that would make sense reading them in the order you recommend.

3. List the five books and their Lexile level. For each book, give a rationale for why you would recommend that book for that student.

*Samples*: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1ro2sNhvP2hGqJBYoAH7wgWbUDz6r8q4j/view?usp=sharing) / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/1SqvwBMFGT5uaUbUUNVFng2h2ZPGqbERv/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1J4IbAS-aVdIqMVrnkw_IlEsQUeE-FU7J/view?usp=sharing) / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/1pmjKpD-8pnRmtzt8oxBqzGDG7vgXBPkJ/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1vTpZF6CphuLMciTpPNlPSlcR4G7hSHag/view?usp=sharing) / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/1RdsqzH3ku6HC3igKSmbypu40KYrqWUVM/view?usp=sharing)

</div>

##### Evidence 2: Annotated Bibliography (ENG 329)
<div style="padding-left:40px;">
*Prompt*

You will sign up for one of the following topics:

1.	What are the best practices (strategies/activities) in assessments for ELA?—Standard 6B
2.	What are best practices (strategies/activities) in **teaching vocabulary** to teens?—Standard 4D

Find at least three scholarly journal articles on that topic and compile the information into an annotated bibliography. Use MLA formatting for citation purposes. OWL@Purdue.edu will help you organize your annotated bibliography. (45 points for bibliography, 15 points for discussion, 60 total)

*Samples*:

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1YxB1NL90MXvaiaKtCpCn_4n5nob3Day6/view?usp=sharing) / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/1ekM0oPfwNK7yHVCnhdAjgTiik4xXLI97/view?usp=sharing)

2. Average performance: [Fall '19](none) / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/1XRCTm0WDGS-1X3w1s-Ix4qReBGNacCy0/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1klVgxvbRqSm5S0Po-ZKRPH89jT4GvVga/view?usp=sharing) / Winter '20 (excused ~ covid-19) / Fall '20 (none)

</div>


##### Evidence 3: Literature Circles - Passage Finder (ENG 356)
<div style="padding-left:40px;">

*Prompt*

Actively participate in novel discussions by completing your assigned group role and speaking in your group discussions. Discussion will take place in class.

1. *Role: Passage Finder and Questioner Lens*: For this role, find 5-8 memorable quotes. Write them in the spaces below. Beside each quote, write a sentence or two **discussing its significance**. (You may **make connections** to your personal context.) Additionally, you must come up with 6 questions about the book that could be discussed. Record the questions below. Write in responses that the group gives you to at least three of the questions. 

*Sample*: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1Iz2o2OZdEa7OyIWcgr7ezt-E3qJ89Pji/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1kX4aVm7H33NIBLDQypPXUHNMV4pr75AN/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1Y0y-SXFrl2oDbyimIKdP3tqPk56wO-Gp/view?usp=sharing)

2. Average Performance: [Fall '19](https://drive.google.com/file/d/11pxDiCQwn_otvdtsep1952SJcDaYDdqW/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1bDxAxBNL0f31JLZo1wlU0LEmOKdoranm/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1jFVn-qsLc7QqEqGOK7zbK6LuCGq_mOuY/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1X5-P1EJU1YYO4yxoVHzk4Ft3lW7k-ME6/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/12r1Yq4Waa9u2cT6gsxarZlG8KAkL0EdN/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1Z4CqIX8vLIYUGDwvmBbdVdM9QDFkcR_B/view?usp=sharing)

</div>


</div>

----

<footer></footer>