---
title: "Standard 1: Learner Development"
output: 
  html_document: 
    theme: cerulean
    css: styles.css
    code_folding: hide
    
---


----

The teacher understands how learners grow and develop, recognizing that patterns of learning and development vary individually within and across the cognitive, linguistic, social, emotional, and physical areas, and designs and implements developmentally appropriate and challenging learning experiences.

----

### {.tabset .tabset-pills .tabset-fade}


#### Performance 1.1

<div style="padding-left:1px;">

Candidates know developmental stages. **Rationale can be found** [**here**](https://drive.google.com/file/d/1tUvBzeqmJOzb70SVDizMe3dBy4rjfN7q/view?usp=sharing)


##### Evidence 1: Writing Sequences (ENG 329)

<div style="padding-left:40px;">

This assignment is lesson planning to teach four genres of writing: fiction, personal narrative, argumentation, and research.  You will plan through five stages, which roughly correspond to pre-writing, writing, editing/evaluation. This will happen in five stages. A sample of this assignment will be provided.

**Samples**: 

1. Excellent performance:  [Fall '19](https://drive.google.com/file/d/14c-s3xbLpPA5GmTEN6by0G7BSe18HE3P/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1ZkdTqUm_k6N3Uq2QtqWo3mNrhPdECVP1/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/164snfLPRmVCQMbRLCWlF2xPX9ahTLw3f/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/17pDWqY7JhXYMGLn_3AsjOaAbq3gZvLbv/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/13kLVUok2JNPxOQon43RJN_5W9mYZGq5b/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1U-7cM_ocCY7GdObsWSbIGkppsgxeb0Z4/view?usp=sharing)

3.  Poor performance: [Fall '19](https://drive.google.com/file/d/1dqjt2gg9v0hybme0MM1qyEYnPlZZ-8_T/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/14Xf-T9mwMUYTRy00l-hR_wAE-KqGKMqo/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1ajT_V8JR9kezP14VQHvnOy9uw4zOAc7w/view?usp=sharing)
</div>

##### Evidence 2: Book Pusher (ENG 356)
<div style="padding-left:40px;">

You must convince your professor that the books you chose will really work for those tough people in those three groups. You will come to Sister Glenn’s office (Rigby 304) or Sara’s office (Rigby 101) on your scheduled test day and time. You will come in, sit down, and roll the die. The number you roll, will indicate which group (1 and 4=young adult, 2 and 5=parent, and 3 and 6=future 356 class) and which three of the nine books you will discuss. After the roll of the die, you will have 10 minutes to talk. You must address these three things in your spiel:

A) Tell Sara or me about the person you are targeting. Be specific so we have a good idea of who this individual is (2 minutes).
B) You must then make your three book recommendations and explain why those are the best choices for the individual you just described (5-6 minutes).
C) At the end, you will discuss some of your findings from your personal reflection (1-2 minutes). 

**Samples**:

A graphical summary of the final grades can be found here: [Fall '19](https://drive.google.com/file/d/1ROFENwvrK2yEhxV6PBFkU7Xk6S-mq-aF/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1zcL25hB-eOFX2v1jauat6HBhcrV8qs3W/view?usp=sharing) / Fall '20 ( [final grades](https://docs.google.com/document/d/1nu5Wwg_Xgr9X71_qDl1Yt_nV546NNcu22l-MFUWUhIM/edit?usp=sharing), [excellent](https://drive.google.com/file/d/1RnOFeVEXZ5FUNGUy26noABL7tczYon5Y/view?usp=sharing), [average](https://drive.google.com/file/d/1JVEc5bYmA6gISUny2pj_cRRueMle5JQa/view?usp=sharing), [poor](https://drive.google.com/file/d/1ICUZ4VXe2ilX00ZXHTbI_YhG73ECgeUg/view?usp=sharing) )





</div>


##### Evidence 3: Lexile Level Text Set (ENG 356)
<div style="padding-left:40px;">

A) As you complete Goodreads, look up and record the Lexile level of each book. 

B) As you complete the 25 books, imagine recommending a series of five books to a specific student. Determine the
grade level and gender of the imagined student you want to write your text set for. Then, choose five books that increase in Lexile level and which are connected thematically in a way that would make sense reading them in the order you recommend. 

C) List the five books and their Lexile level. For each book, give a rationale for why you would recommend that book for that student. 

**Samples**: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1ro2sNhvP2hGqJBYoAH7wgWbUDz6r8q4j/view?usp=sharing) / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/1SqvwBMFGT5uaUbUUNVFng2h2ZPGqbERv/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1J4IbAS-aVdIqMVrnkw_IlEsQUeE-FU7J/view?usp=sharing) / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/1pmjKpD-8pnRmtzt8oxBqzGDG7vgXBPkJ/view?usp=sharing)

3. Poor Performance: [Fall '19](https://drive.google.com/file/d/1vTpZF6CphuLMciTpPNlPSlcR4G7hSHag/view?usp=sharing) / Winter '20 (excused ~ covid-19) / [Fall '20](https://drive.google.com/file/d/1RdsqzH3ku6HC3igKSmbypu40KYrqWUVM/view?usp=sharing)

</div>


</div>

----


#### Performance 1.2

<div style="padding-left:1px;">
Candidates know how adolescents read.
 
##### Evidence 1: Annotated Bibliography Lab (ENG 329)

<div style="padding-left:40px;">

You will sign up for one of the following topics:

*	What are evidence (data and/or numbers) based literacy strategies for teens?—Standard 1B

Find at least three scholarly journal articles on that topic and compile the information into an annotated bibliography. Use MLA formatting for citation purposes. owl@purdue.edu will help you organize your annotated bibliography. 

**Samples**: 

1.Excellent performance: [Fall '19](https://drive.google.com/file/d/1_8-M6l2VX4e1Y7nyk6_Mf_me935PtPOa/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1wtaF5i-Ncrg6gs-RU8-IltoPzLEdmnP0/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1RnOFeVEXZ5FUNGUy26noABL7tczYon5Y/view?usp=sharing) (book pusher)

2.Average performance: [Fall '19](https://drive.google.com/file/d/1rQwp3GVtEOg8p6g6Vs-CpZjp3FONWzb1/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/11FDFSgb-Bn-RRZLLdVSH9ZYZkxNgQE-7/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1JVEc5bYmA6gISUny2pj_cRRueMle5JQa/view?usp=sharing) (book pusher)

3.Poor Performance: [Fall '19](https://drive.google.com/file/d/1VyD9up4sWjAgf-sieXEGj3uQlnxKbLps/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/14-StQ-qge5k4RzIX1hPwPJ2ubBK2OM1Q/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1ICUZ4VXe2ilX00ZXHTbI_YhG73ECgeUg/view?usp=sharing) (book pusher)

</div>

##### Evidence 2: Literature Circles ~ LitLinks role (ENG 356)
<div style="padding-left:40px;">


Publishers, editors, writers, and teachers work together when it comes to using Young Adult Literature in a classroom. Any of these groups of  people post teaching ideas online.  For this literature circle role, you will create a document that gives links and advice on teaching a Young Adult novel. 

Parts of the LitLinks:

1.	Title and Summary. Please provide a brief summary of the text. -3 points
2.	Links to sites about two different themes in the book. Please provide a description of the links. If possible, provide modern day connections. –10 points
3.	Links to at least two teaching ideas. Please provide a description of the links. Choose activities that would serve a diverse group. –12 points

**Samples**:

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1vsU6LV1xoRqCD-rE-eS0lQIT02w67gX6/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1Yawq5PqjscSCQaU16jXqCLvYZaohNzcK/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/12fYlLrJ4-2FTNh1MMXDIz4CR6-THwirn/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1pZbtcAj85PTEt-XA4InYzVupzMEQDItn/view?usp=sharing)  / [Winter '20](https://drive.google.com/file/d/1FMncORFpmEH6pDzxbUMxcxCjI3uZkyUJ/view?usp=sharing)/ [Fall '20](https://drive.google.com/file/d/18reC5uGSOExvvIBoUpcebajIN1LQo5nr/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1eYqYIrtLYLpfxvu_qJcchiRELGZvIdY3/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1SCmqaSPVEvI8dUBSa0KIJMYgYRglssKV/view?usp=sharing)/ [Fall '20](https://drive.google.com/file/d/1iBiv6rywfTjnGF6n6bahqSxtUUH-BUK4/view?usp=sharing)
</div>


##### Evidence 3: Goodreads (ENG 356)
<div style="padding-left:40px;">


This semester you will read 20 YA books.Many of these are not difficult to read, but it is essential that you keep up with both the reading and the assignments.  In order to stay on top of things, plan to read two books per week. That pace should keep you from grief at the end of the semester. (10 points per book, 200 total/20 points for the Reading Record) 

20 books:

A)	8 class assigned books  (the 9th  and 10th will be books of your choice in connection to our multicultural book studies)
B)	1 book from Honor List (or other award winner)—please mark on reading record
C)	8 books your choice—various genres, time periods—please mark on reading record
D)	1 censored book (in addition to I am the Cheese)—please mark on reading record

NOTE: Please do not read books in which you have already read or seen the movie (Harry Potter series, Hunger Games series, The Giver quartet, Maze Runner series, Twilight Series, etc.). Where you are already familiar with these books/movies, do yourself a favor and branch out—read something new. This will benefit you in the end. 

**Samples**:

1. Excellent Performance: [Fall '19](https://www.goodreads.com/review/list/96688926?shelf=books-1-10) / [Winter '20](https://www.goodreads.com/review/list/108466313?shelf=books-1-10) / [Fall '20](https://www.goodreads.com/review/list/121519345-madeline-bourgeous?order=d&sort=review&view=reviews)

2. Average Performance: [Fall '19](https://www.goodreads.com/review/list/96494563?shelf=1-10-reads) / [Winter '20](https://www.goodreads.com/review/list/108466440?shelf=books-1-10) / [Fall '20](https://www.goodreads.com/review/list/113307900-kali-adams?order=d&sort=review&view=reviews)

3. Poor Performance: [Fall '19](https://www.goodreads.com/review/list/5294647?shelf=books-1-10) / [Winter '20](https://www.goodreads.com/review/list/108466310?shelf=books-1-10) / [Fall '20](https://www.goodreads.com/review/list/121511521-deanna-lamalfa?order=d&sort=review&view=reviews)
</div>


</div>


----



#### Performance 1.3

<div style="padding-left:1px;">
Candidates know how adolescents compose texts.
 
 

##### Evidence 1: Writing Unit (ENG 329)

<div style="padding-left:40px;">


Each student will participate in developing a group writing unit.  Each student will be responsible for a personal section of the unit, as well as the overall unit.  Each group will develop a unit for a specific type of writing, complete with goals, pre-writing and writing activities, *a technology piece*, evaluations/assessments, and accommodations for students.  The group will establish goals for the writing unit, a reflective piece, and a rubric for grading the writing.  The individual members of the group will each find or develop pre-writing activities, writing activities, evaluations/assessments and accommodations for students.  Each student will receive both an individual and a group grade. 


**Samples**: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1Ikk3WzOdfRHMjIUff8vMC-3Qe2_uSbI-/view?usp=sharing) / Winter '20 (not used this semester) / Fall '20 (not used this semester)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1DlzU96QTgm9QeO200YXII3wHz4WLZDJP/view?usp=sharing) / Winter '20 (not used this semester) / Fall '20 (not used this semester)

3. Poor Performance: [Fall '19](https://drive.google.com/file/d/180NVk5dWLWIbTVTldcIWgzWGYWlMF082/view?usp=sharing) / Winter '20 (not used this semester) / Fall '20 (not used this semester)

</div>

##### Evidence 2: Annotated Bibliography (ENG 329)
<div style="padding-left:40px;">


You will sign up for one of the following topics:


*	What are evidence (data and/or numbers) based  literacy strategies for teens?—Standard 1B
*	How do language and dialect affect literacy?—Standards 2A and 3A


Find at least three scholarly journal articles on that topic and compile the information into an annotated bibliography. Use MLA formatting for citation purposes. OWL@Purdue.edu will help you organize your annotated bibliography.   

**Samples**:

1. Excellent Performance: [Fall '19](https://drive.google.com/file/d/1_8-M6l2VX4e1Y7nyk6_Mf_me935PtPOa/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1Iyt9z9wStHvrWzypJQYhpb8ENbIYGef5/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/13VZLyMig1PvFeVyamKfc7gy3mi9o3Qn-/view?usp=sharing)

2. Average Performance: [Fall '19](https://drive.google.com/file/d/1rQwp3GVtEOg8p6g6Vs-CpZjp3FONWzb1/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1KkQkrk1Sph_BRmLzRc56Le3uzRmxqlPk/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/13VZLyMig1PvFeVyamKfc7gy3mi9o3Qn-/view?usp=sharing)

3. Poor Performance: [Fall '19](https://drive.google.com/file/d/1G84mOFKFVuzOW7pgDjmMW_bv8RtDpoEq/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1FAKXipnjGQF_xJ59WIHFuz496T9-ecBR/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1zbvvvr4qqfY0BDEdt9e-KLRZLHJuXb58/view?usp=sharing)

</div>


##### Evidence 3: Writing Sequences (ENG 329)
<div style="padding-left:40px;">

This assignment is lesson planning to teach four genres of writing: fiction, personal narrative, argumentation, and research.  You will plan through five stages, which roughly correspond to pre-writing, writing, editing/evaluation. This will happen in five stages. A sample of this assignment will be provided.

**Samples**: 

1. Excellent performance:  [Fall '19](https://drive.google.com/file/d/14c-s3xbLpPA5GmTEN6by0G7BSe18HE3P/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1ZkdTqUm_k6N3Uq2QtqWo3mNrhPdECVP1/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/164snfLPRmVCQMbRLCWlF2xPX9ahTLw3f/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/17pDWqY7JhXYMGLn_3AsjOaAbq3gZvLbv/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/13kLVUok2JNPxOQon43RJN_5W9mYZGq5b/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1U-7cM_ocCY7GdObsWSbIGkppsgxeb0Z4/view?usp=sharing)

3.  Poor performance: [Fall '19](https://drive.google.com/file/d/1dqjt2gg9v0hybme0MM1qyEYnPlZZ-8_T/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/14Xf-T9mwMUYTRy00l-hR_wAE-KqGKMqo/view?usp=sharing) / [Fall '20](https://drive.google.com/file/d/1ajT_V8JR9kezP14VQHvnOy9uw4zOAc7w/view?usp=sharing)
</div>


</div>

----

<footer></footer>