---
title: "Standard 9: Professional Learning and Ethical Practice"
output: 
  html_document: 
    theme: cerulean
    css: styles.css
---

<script type="text/javascript">
 function showhide(id) {
    var e = document.getElementById(id);
    e.style.display = (e.style.display == 'block') ? 'none' : 'block';
 }
</script>

----
 
The teacher engages in ongoing professional learning and uses evidence to continually evaluate his/her practice, particularly the effects of his/her choices and actions on others (learners, families, other professionals, and the community), and adapts practice to meet the needs of each learner.  

----

### {.tabset .tabset-pills .tabset-fade}


#### Performance 9.1

<div style="padding-left:1px;">

Candidates model literate and ethical practices in ELA teaching. 

##### Evidence 1: Teaching/Practicum Lab (1-3) (ENG 329/430)

<div style="padding-left:40px;">

**Prompt**

You will teach a minimum of three times. You can work this out with your mentor teacher. This may be for a full or partial class period. Please submit your lesson plan to me via email three days in advance of teaching. Then, I can give you some feedback and your mentor teacher can give you some feedback. Remember, your mentor teacher is still held responsible for what you teach—please make him or her a big part of your planning process. These elements need to be in your lesson plan to receive full credit: objective, standard, assessment, hook, I DO, WE DO, THEY DO, closure, and enough detail that a sub could teach your lesson. You may want to ask your mentor teacher for lesson plan templates that have been helpful to him or her. (Standard 8A (Parts of 4 and 5—depending on the lesson)).

**Samples**: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/1Lm4FBpGrbs5UKWAvZWOJdHZ0mCs4srey/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1cLQaxNW1zg3W_Ot-8YF8TolAbDtNjrUL/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1AXmrAjV4atv_CzL8goaZ8xWc8f-jl037/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/15MqYL_PdT89n7Cd4e3fo9N8bps8LwLY6/view?usp=sharing)

3. Poor Performance: [Fall '19](https://drive.google.com/file/d/1ZNBRP6kwscIzd3I_ebM96IDSuib0P6YK/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1dp7Z_ox3pJI75idKpMHATdS2xADfSTdu/view?usp=sharing) 
</div>

##### Evidence 2: PowerPoint on Code of Ethics (ENG 329)
<div style="padding-left:40px;">

Students review some standars for professionalism using this [PowerPoint](https://drive.google.com/file/d/1I5IEZdfngW4l-3MtdGiqoN2XGHEOmZ23/view?usp=sharing)

</div>


##### Evidence 3: Observations (11-15) (ENG 329/430)
<div style="padding-left:40px;">
**Prompt**

Fifteen observations in an ELA classroom setting with a mentor teacher. All observations will be one to two pages in length when typed. All observations must be submitted by midnight of November 18. Use these observations below:

1. Briefly describe one aspect that you believe went well during today’s class (3-5 sentences).  Reference  the  Domain/Component  that  aligns  with  this  aspect  of  your  experience  (i.e.  2a: Creating an Environment of Respect and Rapport).

2. Briefly  describe  a  second  aspect  that  you  believe  went  well  during  today’s  class  (3-5 sentences).      Reference   the   Domain/Component   that   aligns   with   this   aspect   of   your experience (i.e. 2a: Creating an Environment of Respect and Rapport).

3. Identify and briefly describe one aspect of the teacher’s rapport (relationship) with students that you would like to incorporate in your teaching (3-5 sentences).

4. Research indicates that engagement in learning is enhanced by addressing one or more of the following  areas:    Activities/Assignments,  Grouping  of  Students,  Resources/Materials,  and Pacing.    Select  one  that  you  believe  improved  the  level  of  student  engagement  of  today’s lesson and briefly describe what how the teacher incorporated it in the lesson.

5. Describe the teacher’s “persona” (demeanor).  How was s/he able to maintain discipline in the  classroom  nonverbally?    What  in  his/her  clothing  allowed  them  to  focus  on  students rather than on themselves?

**Samples**: 

1. Excellent performance: [Fall '19](https://drive.google.com/file/d/15dRr5V5DhrEP8OELI4tMvWP8rTE-s2F6/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1o1N3yGnuEgfWX-4iSsv9JUm1aGIUBdcT/view?usp=sharing)

2. Average performance: [Fall '19](https://drive.google.com/file/d/1y6PT5760qgzhQfAEcExl5TTrEmgtqsoz/view?usp=sharing) /  [Winter '20](https://drive.google.com/file/d/13la0WDfAo_Uov73Cd2hz99PuX5Xnq9HR/view?usp=sharing)

3. Poor performance: [Fall '19](https://drive.google.com/file/d/1_XF-VIuPKYtf4yMIkIBuauX9msINeHW7/view?usp=sharing) / [Winter '20](https://drive.google.com/file/d/1Z8QmVgrQ_k-2cSVxQVRRdbP6CXr3Oy9q/view?usp=sharing)


</div>


##### Evidence 4?: to be determined
<div style="padding-left:40px;">
**Prompt**
Course Attendance is not available on Canvas for the Year 2019. 

**Excellent Performance (sample)**

**Average Performance (sample)**

**Poor Performance (sample)**
</div>

</div>

----

<footer></footer>